#!/usr/bin/env python3
"""Writes cc/include/arm_neon.h, sicc's NEON intrinsics for AArch64: the
types (int8x16_t...) and functions (vaddq_s32...), each one sicc vector
operator or __builtin_neon (one NEON instruction). Run after changing the
VOP_* list in cc/sicc.h: the operation numbers must match.
Usage: mkneon.py > cc/include/arm_neon.h
Part of SIEOS. SPDX-License-Identifier: GPL-3.0-only"""
import re, sys, os

here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, "..", "..", "cc", "sicc.h")).read()
body = src[src.index("enum { VOP_ADD"):]
body = body[:body.index("VOP_COUNT")]
body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)
ops = re.findall(r"VOP_(\w+)", body)

T = {  # suffix: (C element type, bytes, kind) kind: s, u, f, h (half: unsigned short bits)
    "s8": ("signed char", 1, "s"), "u8": ("unsigned char", 1, "u"), "s16": ("short", 2, "s"), "u16": ("unsigned short", 2, "u"),
    "s32": ("int", 4, "s"), "u32": ("unsigned", 4, "u"), "s64": ("long", 8, "s"), "u64": ("unsigned long", 8, "u"),
    "f32": ("float", 4, "f"), "f64": ("double", 8, "f"),
}
INTS = ["s8", "u8", "s16", "u16", "s32", "u32", "s64", "u64"]
SMALL = ["s8", "u8", "s16", "u16", "s32", "u32"]        # elements a NEON instruction multiplies, widens...
ALL = INTS + ["f32", "f64"]

def vt(t, q):
    c, n, k = T[t]
    base = {"s": "int", "u": "uint", "f": "float"}[k]
    return f"{base}{n * 8}x{(16 if q else 8) // n}_t"
def lanes(t, q): return (16 if q else 8) // T[t][1]
def wide(t): return {"s8": "s16", "u8": "u16", "s16": "s32", "u16": "u32", "s32": "s64", "u32": "u64"}[t]
def narrow(t): return {"s16": "s8", "u16": "u8", "s32": "s16", "u32": "u16", "s64": "s32", "u64": "u32"}[t]
def utype(t): return "u" + t[1:] if t[0] in "su" else {"f32": "u32", "f64": "u64"}[t]
def stype(t): return "s" + t[1:] if t[0] in "su" else {"f32": "s32", "f64": "s64"}[t]

o = []
w = o.append
w("""/* arm_neon.h - NEON intrinsics for sicc on AArch64 (generated by
 * tools/cc/mkneon.py: do not edit). Each function is one vector operator or
 * one __builtin_neon(operation, (result type *)0, a, b, accumulator, imm),
 * which becomes one NEON instruction. Vectors are values like structs; the
 * functions are always inlined. float16x4_t/float16x8_t hold half-precision
 * bits (unsigned short): vcvt_f32_f16 and vcvt_f16_f32 convert them.
 * The dot product (vdotq_s32...) needs -march=armv8.2-a+dotprod.
 * Part of SIEOS. SPDX-License-Identifier: GPL-3.0-only */
#ifndef _ARM_NEON_H
#define _ARM_NEON_H
#ifndef __aarch64__
#error "arm_neon.h: AArch64 only"
#endif
""")
w("enum { " + ", ".join(f"__NOP_{x}" for x in ops) + " };")
w("void *memcpy(void *, const void *, __SIZE_TYPE__);  /* (small and constant: inlined) */")
w("#define __SI static __inline__ __attribute__((always_inline))")
w("#define __N(op, T, a, b, c, i) __builtin_neon(__NOP_##op, (T *)0, a, b, c, i)")
w("#define __V(op, a, b) __builtin_vec(__NOP_##op, a, b, 0)")
w("")
for t in ALL:
    for q in (0, 1):
        w(f"typedef {T[t][0]} {vt(t, q)} __attribute__((vector_size({16 if q else 8})));")
w("typedef unsigned short float16x4_t __attribute__((vector_size(8)));")
w("typedef unsigned short float16x8_t __attribute__((vector_size(16)));")
w("")

for t in ALL:
    c, n, k = T[t]
    for q in (0, 1):
        V, Q, L, sz = vt(t, q), "q" if q else "", lanes(t, q), 16 if q else 8
        U = vt(utype(t), q)
        f = lambda name: "v" + name.split("_", 1)[0] + Q + "".join("_" + x for x in name.split("_", 1)[1:]) + "_" + t   # vdupq_n_s8
        w(f"/* {V} */")
        w(f"__SI {V} {f('ld1')}(const {c} *p) {{ {V} r; memcpy(&r, p, {sz}); return r; }}")
        w(f"__SI void {f('st1')}({c} *p, {V} a) {{ memcpy(p, &a, {sz}); }}")
        w(f"__SI {V} {f('dup_n')}({c} x) {{ return __N(SPLAT, {V}, x, 0, 0, 0); }}")
        w(f"__SI {V} {f('mov_n')}({c} x) {{ return {f('dup_n')}(x); }}")
        w(f"__SI {V} {f('ld1_dup')}(const {c} *p) {{ return {f('dup_n')}(*p); }}")
        w(f"__SI {V} {f('add')}({V} a, {V} b) {{ return a + b; }}")
        w(f"__SI {V} {f('sub')}({V} a, {V} b) {{ return a - b; }}")
        w(f"__SI {V} {f('mul')}({V} a, {V} b) {{ return a * b; }}")
        w(f"__SI {U} {f('ceq')}({V} a, {V} b) {{ return ({U})(a == b); }}")
        w(f"__SI {U} {f('cgt')}({V} a, {V} b) {{ return ({U})(a > b); }}")
        w(f"__SI {U} {f('cge')}({V} a, {V} b) {{ return ({U})(a >= b); }}")
        w(f"__SI {U} {f('clt')}({V} a, {V} b) {{ return ({U})(a < b); }}")
        w(f"__SI {U} {f('cle')}({V} a, {V} b) {{ return ({U})(a <= b); }}")
        w(f"__SI {V} {f('bsl')}({U} m, {V} a, {V} b) {{ return __N(BSL, {V}, a, b, ({V})m, 0); }}")
        w(f"__SI {V} {f('zip1')}({V} a, {V} b) {{ return __V(UNPCKLO, a, b); }}")
        w(f"__SI {V} {f('zip2')}({V} a, {V} b) {{ return __V(UNPCKHI, a, b); }}")
        for p in ("uzp1", "uzp2", "trn1", "trn2"):
            w(f"__SI {V} {f(p)}({V} a, {V} b) {{ return __N({p.upper()}, {V}, a, b, 0, 0); }}")
        w(f"#define {f('ext')}(a, b, n) __N(EXT, {V}, ({V})(a), ({V})(b), 0, (n) * {n})")
        w(f"#define {f('get_lane' if not q else 'getq_lane'.replace('q_', '_'))}(a, n) (({V})(a))[n]" if False else
          f"#define v{'getq' if q else 'get'}_lane_{t}(a, n) ((({V})(a))[n])")
        w(f"#define v{'setq' if q else 'set'}_lane_{t}(x, a, n) ({{ {V} __t = (a); __t[n] = (x); __t; }})")
        w(f"#define v{'dupq' if q else 'dup'}_lane{'q' if q else ''}_{t}(a, n) __N(DUPL, {V}, ({V})(a), 0, 0, n)")
        w(f"__SI {V} {f('padd')}({V} a, {V} b) {{ return __N(ADDP, {V}, a, b, 0, 0); }}")
        if n <= 4 or q:
            w(f"__SI {c} {f('addv')}({V} a) {{ return __N(ADDV, {c}, a, 0, 0, 0); }}")
        if k == "f":
            w(f"__SI {V} {f('div')}({V} a, {V} b) {{ return a / b; }}")
            w(f"__SI {V} {f('neg')}({V} a) {{ return -a; }}")
            w(f"__SI {V} {f('abs')}({V} a) {{ return __V(ABS, a, a); }}")
            w(f"__SI {V} {f('sqrt')}({V} a) {{ return __V(SQRT, a, a); }}")
            w(f"__SI {V} {f('max')}({V} a, {V} b) {{ return __V(MAX, a, b); }}")
            w(f"__SI {V} {f('min')}({V} a, {V} b) {{ return __V(MIN, a, b); }}")
            w(f"__SI {V} {f('mul_n')}({V} a, {c} x) {{ return a * x; }}")
            w(f"__SI {V} {f('mla')}({V} a, {V} b, {V} c) {{ return a + b * c; }}")
            w(f"__SI {V} {f('fma')}({V} a, {V} b, {V} c) {{ return __N(FMA, {V}, b, c, a, 0); }}")
            w(f"__SI {V} {f('fms')}({V} a, {V} b, {V} c) {{ return __N(FMS, {V}, b, c, a, 0); }}")
            w(f"__SI {V} {f('fma_n')}({V} a, {V} b, {c} x) {{ return __N(FMA, {V}, b, {f('dup_n')}(x), a, 0); }}")
            S, UU = vt(stype(t), q), vt(utype(t), q)
            w(f"__SI {V} vcvt{Q}_{t}_{stype(t)}({S} a) {{ return __N(CVTI2F, {V}, a, 0, 0, 0); }}")
            w(f"__SI {V} vcvt{Q}_{t}_{utype(t)}({UU} a) {{ return __N(CVTI2F, {V}, a, 0, 0, 0); }}")
            w(f"__SI {S} vcvt{Q}_{stype(t)}_{t}({V} a) {{ return __N(CVTF2I, {S}, a, 0, 0, 0); }}")
            w(f"__SI {UU} vcvt{Q}_{utype(t)}_{t}({V} a) {{ return __N(CVTF2I, {UU}, a, 0, 0, 1); }}")
            w(f"__SI {S} vcvtn{Q}_{stype(t)}_{t}({V} a) {{ return __N(CVTF2IR, {S}, a, 0, 0, 0); }}")
        else:
            S = vt(stype(t), q)
            w(f"__SI {V} {f('and')}({V} a, {V} b) {{ return a & b; }}")
            w(f"__SI {V} {f('orr')}({V} a, {V} b) {{ return a | b; }}")
            w(f"__SI {V} {f('eor')}({V} a, {V} b) {{ return a ^ b; }}")
            w(f"__SI {V} {f('bic')}({V} a, {V} b) {{ return __V(ANDNOT, b, a); }}")
            w(f"__SI {V} {f('mvn')}({V} a) {{ return ~a; }}")
            w(f"#define {f('shl_n')}(a, n) (({V})(a) << (n))")
            w(f"#define {f('shr_n')}(a, n) (({V})(a) >> (n))")
            w(f"__SI {V} {f('shl')}({V} a, {S} b) {{ return __V(SHL, a, ({V})b); }}")
            w(f"__SI {V} {f('qadd')}({V} a, {V} b) {{ return __V(ADDS, a, b); }}")
            w(f"__SI {V} {f('qsub')}({V} a, {V} b) {{ return __V(SUBS, a, b); }}")
            if k == "s":
                w(f"__SI {V} {f('neg')}({V} a) {{ return -a; }}")
                w(f"__SI {V} {f('abs')}({V} a) {{ return __V(ABS, a, a); }}")
            if n <= 4:
                w(f"__SI {V} {f('max')}({V} a, {V} b) {{ return __V(MAX, a, b); }}")
                w(f"__SI {V} {f('min')}({V} a, {V} b) {{ return __V(MIN, a, b); }}")
                w(f"__SI {V} {f('rhadd')}({V} a, {V} b) {{ return __V(AVG, a, b); }}")
                w(f"__SI {V} {f('mla')}({V} a, {V} b, {V} c) {{ return __N(MLA, {V}, b, c, a, 0); }}")
                w(f"__SI {V} {f('mls')}({V} a, {V} b, {V} c) {{ return __N(MLS, {V}, b, c, a, 0); }}")
            if n == 1:
                w(f"__SI {V} {f('cnt')}({V} a) {{ return __N(CNT, {V}, a, 0, 0, 0); }}")
            if t in SMALL:
                W = vt(wide(t), q)
                w(f"__SI {W} {f('paddl')}({V} a) {{ return __N(PADDL, {W}, a, 0, 0, 0); }}")
                w(f"__SI {W} {f('padal')}({W} acc, {V} a) {{ return __N(PADAL, {W}, a, 0, acc, 0); }}")
        w("")
    if t in SMALL:                                    # widening and narrowing, between 8- and 16-byte vectors
        V8, V16, W = vt(t, 0), vt(t, 1), vt(wide(t), 1)
        w(f"__SI {W} vmull_{t}({V8} a, {V8} b) {{ return __N(MULL, {W}, a, b, 0, 0); }}")
        w(f"__SI {W} vmull_high_{t}({V16} a, {V16} b) {{ return __N(MULL2, {W}, a, b, 0, 0); }}")
        w(f"__SI {W} vmlal_{t}({W} acc, {V8} a, {V8} b) {{ return __N(MLAL, {W}, a, b, acc, 0); }}")
        w(f"__SI {W} vmlal_high_{t}({W} acc, {V16} a, {V16} b) {{ return __N(MLAL2, {W}, a, b, acc, 0); }}")
        w(f"__SI {W} vmovl_{t}({V8} a) {{ return __N(MOVL, {W}, a, 0, 0, 0); }}")
        w(f"__SI {W} vmovl_high_{t}({V16} a) {{ return __N(MOVL2, {W}, a, 0, 0, 0); }}")
    if t in INTS and T[t][1] >= 2:
        N8, V16 = vt(narrow(t), 0), vt(t, 1)
        w(f"__SI {N8} vmovn_{t}({V16} a) {{ return __N(XTN, {N8}, a, 0, 0, 0); }}")
        w(f"__SI {N8} vqmovn_{t}({V16} a) {{ return __N(QXTN, {N8}, a, 0, 0, 0); }}")
        if T[t][2] == "s":
            UN8 = vt(utype(narrow(t)), 0)
            w(f"__SI {UN8} vqmovun_{t}({V16} a) {{ return __N(QXTUN, {UN8}, a, 0, 0, 0); }}")
    # halves
    V8, V16 = vt(t, 0), vt(t, 1)
    w(f"__SI {V8} vget_low_{t}({V16} a) {{ {V8} r; memcpy(&r, &a, 8); return r; }}")
    w(f"__SI {V8} vget_high_{t}({V16} a) {{ {V8} r; memcpy(&r, (char *)&a + 8, 8); return r; }}")
    w(f"__SI {V16} vcombine_{t}({V8} lo, {V8} hi) {{ {V16} r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }}")
    w("")

w("/* tables, half precision, reinterpretation */")
w("__SI uint8x16_t vqtbl1q_u8(uint8x16_t t, uint8x16_t i) { return __N(TBL, uint8x16_t, t, i, 0, 0); }")
w("__SI uint8x8_t vqtbl1_u8(uint8x16_t t, uint8x8_t i) { return __N(TBL, uint8x8_t, t, i, 0, 0); }")
w("__SI int8x16_t vqtbl1q_s8(int8x16_t t, uint8x16_t i) { return __N(TBL, int8x16_t, t, i, 0, 0); }")
w("__SI int8x8_t vqtbl1_s8(int8x16_t t, uint8x8_t i) { return __N(TBL, int8x8_t, t, i, 0, 0); }")
w("__SI float32x4_t vcvt_f32_f16(float16x4_t a) { return __N(FCVTL, float32x4_t, a, 0, 0, 0); }")
w("__SI float32x4_t vcvt_high_f32_f16(float16x8_t a) { return __N(FCVTL2, float32x4_t, a, 0, 0, 0); }")
w("__SI float16x4_t vcvt_f16_f32(float32x4_t a) { return __N(FCVTN, float16x4_t, a, 0, 0, 0); }")
w("__SI float16x4_t vld1_f16(const void *p) { float16x4_t r; memcpy(&r, p, 8); return r; }")
w("__SI float16x8_t vld1q_f16(const void *p) { float16x8_t r; memcpy(&r, p, 16); return r; }")
w("__SI void vst1_f16(void *p, float16x4_t a) { memcpy(p, &a, 8); }")
w("__SI float16x4_t vget_low_f16(float16x8_t a) { float16x4_t r; memcpy(&r, &a, 8); return r; }")
w("__SI float16x4_t vget_high_f16(float16x8_t a) { float16x4_t r; memcpy(&r, (char *)&a + 8, 8); return r; }")
for q in (0, 1):
    names = ALL + ["f16"]
    for a in names:
        for b in names:
            if a == b: continue
            A = vt(a, q) if a != "f16" else ("float16x8_t" if q else "float16x4_t")
            w(f"#define vreinterpret{'q' if q else ''}_{a}_{b}(x) (({A})(x))")
w("""
#ifdef __ARM_FEATURE_DOTPROD
/* the dot product (ARMv8.2): each 32-bit lane += the sum of 4 byte products */
__SI int32x4_t vdotq_s32(int32x4_t acc, int8x16_t a, int8x16_t b) { return __N(DOT, int32x4_t, a, b, acc, 0); }
__SI uint32x4_t vdotq_u32(uint32x4_t acc, uint8x16_t a, uint8x16_t b) { return __N(DOT, uint32x4_t, a, b, acc, 0); }
__SI int32x2_t vdot_s32(int32x2_t acc, int8x8_t a, int8x8_t b) { return __N(DOT, int32x2_t, a, b, acc, 0); }
__SI uint32x2_t vdot_u32(uint32x2_t acc, uint8x8_t a, uint8x8_t b) { return __N(DOT, uint32x2_t, a, b, acc, 0); }
#define vdotq_laneq_s32(acc, a, b, n) __N(DOTL, int32x4_t, (int8x16_t)(a), (int8x16_t)(b), (int32x4_t)(acc), n)
#define vdotq_laneq_u32(acc, a, b, n) __N(DOTL, uint32x4_t, (uint8x16_t)(a), (uint8x16_t)(b), (uint32x4_t)(acc), n)
#define vdotq_lane_s32(acc, a, b, n) __N(DOTL, int32x4_t, (int8x16_t)(a), (int8x8_t)(b), (int32x4_t)(acc), n)
#endif
#endif""")
print("\n".join(o))
