/*
 * sieos/errno.h - Error numbers (ABI v2).  Values follow Solaris.
 */
#ifndef SIEOS_ABI_ERRNO_H
#define SIEOS_ABI_ERRNO_H

#define SIEOS_EPERM            1
#define SIEOS_ENOENT           2
#define SIEOS_ESRCH            3
#define SIEOS_EINTR            4
#define SIEOS_EIO              5
#define SIEOS_ENXIO            6
#define SIEOS_E2BIG            7
#define SIEOS_ENOEXEC          8
#define SIEOS_EBADF            9
#define SIEOS_ECHILD          10
#define SIEOS_EAGAIN          11
#define SIEOS_EWOULDBLOCK     SIEOS_EAGAIN
#define SIEOS_ENOMEM          12
#define SIEOS_EACCES          13
#define SIEOS_EFAULT          14
#define SIEOS_ENOTBLK         15
#define SIEOS_EBUSY           16
#define SIEOS_EEXIST          17
#define SIEOS_EXDEV           18
#define SIEOS_ENODEV          19
#define SIEOS_ENOTDIR         20
#define SIEOS_EISDIR          21
#define SIEOS_EINVAL          22
#define SIEOS_ENFILE          23
#define SIEOS_EMFILE          24
#define SIEOS_ENOTTY          25
#define SIEOS_ETXTBSY         26
#define SIEOS_EFBIG           27
#define SIEOS_ENOSPC          28
#define SIEOS_ESPIPE          29
#define SIEOS_EROFS           30
#define SIEOS_EMLINK          31
#define SIEOS_EPIPE           32
#define SIEOS_EDOM            33
#define SIEOS_ERANGE          34
#define SIEOS_ENOMSG          35
#define SIEOS_EIDRM           36
#define SIEOS_ECHRNG          37
#define SIEOS_EL2NSYNC        38
#define SIEOS_EL3HLT          39
#define SIEOS_EL3RST          40
#define SIEOS_ELNRNG          41
#define SIEOS_EUNATCH         42
#define SIEOS_ENOCSI          43
#define SIEOS_EL2HLT          44
#define SIEOS_EDEADLK         45
#define SIEOS_ENOLCK          46
#define SIEOS_ECANCELED       47
#define SIEOS_ENOTSUP         48
#define SIEOS_EDQUOT          49
#define SIEOS_EBADE           50
#define SIEOS_EBADR           51
#define SIEOS_EXFULL          52
#define SIEOS_ENOANO          53
#define SIEOS_EBADRQC         54
#define SIEOS_EBADSLT         55
#define SIEOS_EDEADLOCK       56
#define SIEOS_EBFONT          57
#define SIEOS_EOWNERDEAD      58
#define SIEOS_ENOTRECOVERABLE 59
#define SIEOS_ENOSTR          60
#define SIEOS_ENODATA         61
#define SIEOS_ETIME           62
#define SIEOS_ENOSR           63
#define SIEOS_ENONET          64
#define SIEOS_ENOPKG          65
#define SIEOS_EREMOTE         66
#define SIEOS_ENOLINK         67
#define SIEOS_EADV            68
#define SIEOS_ESRMNT          69
#define SIEOS_ECOMM           70
#define SIEOS_EPROTO          71
#define SIEOS_ELOCKUNMAPPED   72
#define SIEOS_ENOTACTIVE      73
#define SIEOS_EMULTIHOP       74
#define SIEOS_EBADMSG         77
#define SIEOS_ENAMETOOLONG    78
#define SIEOS_EOVERFLOW       79
#define SIEOS_ENOTUNIQ        80
#define SIEOS_EBADFD          81
#define SIEOS_EREMCHG         82
#define SIEOS_ELIBACC         83
#define SIEOS_ELIBBAD         84
#define SIEOS_ELIBSCN         85
#define SIEOS_ELIBMAX         86
#define SIEOS_ELIBEXEC        87
#define SIEOS_EILSEQ          88
#define SIEOS_ENOSYS          89
#define SIEOS_ELOOP           90
#define SIEOS_ERESTART        91
#define SIEOS_ESTRPIPE        92
#define SIEOS_ENOTEMPTY       93
#define SIEOS_EUSERS          94
#define SIEOS_ENOTSOCK        95
#define SIEOS_EDESTADDRREQ    96
#define SIEOS_EMSGSIZE        97
#define SIEOS_EPROTOTYPE      98
#define SIEOS_ENOPROTOOPT     99
#define SIEOS_EPROTONOSUPPORT 120
#define SIEOS_ESOCKTNOSUPPORT 121
#define SIEOS_EOPNOTSUPP      122
#define SIEOS_EPFNOSUPPORT    123
#define SIEOS_EAFNOSUPPORT    124
#define SIEOS_EADDRINUSE      125
#define SIEOS_EADDRNOTAVAIL   126
#define SIEOS_ENETDOWN        127
#define SIEOS_ENETUNREACH     128
#define SIEOS_ENETRESET       129
#define SIEOS_ECONNABORTED    130
#define SIEOS_ECONNRESET      131
#define SIEOS_ENOBUFS         132
#define SIEOS_EISCONN         133
#define SIEOS_ENOTCONN        134
#define SIEOS_ESHUTDOWN       143
#define SIEOS_ETOOMANYREFS    144
#define SIEOS_ETIMEDOUT       145
#define SIEOS_ECONNREFUSED    146
#define SIEOS_EHOSTDOWN       147
#define SIEOS_EHOSTUNREACH    148
#define SIEOS_EALREADY        149
#define SIEOS_EINPROGRESS     150
#define SIEOS_ESTALE          151

#define SIEOS_ELAST           151

#endif
