"""The calling convention, both ways: random function signatures (scalars,
floats, structs and unions of every shape, many arguments: some on the stack,
struct results, variadic calls) in two files, a caller and a callee; built
with the callee by sicc and the caller by the host compiler, then the other
way round. Both must print what the host compiler alone prints.
Usage: abigen.py SICC [cases] [seed]. Part of SIEOS. (c) Olivier Moulin. SPDX-License-Identifier: GPL-3.0-only"""
import random, subprocess, sys, os
sicc = sys.argv[1]
ncase = int(sys.argv[2]) if len(sys.argv) > 2 else 40
random.seed(int(sys.argv[3]) if len(sys.argv) > 3 else 7)
out = os.environ.get("OUT", "/tmp/sicc-abi")
os.makedirs(out, exist_ok=True)
SCAL = ["char", "signed char", "unsigned char", "short", "unsigned short", "int", "unsigned", "long", "unsigned long", "float", "double", "long double", "_Bool"]
structs, decls, members = [], [], {}

def mkstruct():
    k = len(structs)
    n = random.randint(1, 5)
    mem = []
    for i in range(n):
        t = random.choice(SCAL[:11] + ["arr", "nest"] if structs else SCAL[:11] + ["arr"])
        if t == "arr": mem.append((random.choice(["char", "short", "int", "float", "double"]), f"m{i}", random.randint(1, 4)))
        elif t == "nest": mem.append((random.choice(structs), f"m{i}", 0))
        else: mem.append((t, f"m{i}", 0))
    kind = "union" if random.random() < 0.15 else "struct"
    name = f"{kind} S{k}"
    decls.append(name + " { " + " ".join(f"{t} {m}" + (f"[{a}]" if a else "") + ";" for t, m, a in mem) + " };")
    structs.append(name)
    members[name] = mem if kind == "struct" else mem[:1]     # (a union: its first member)
    return name

for _ in range(14): mkstruct()

def val(t, seed):
    """an expression that fills a value of type t (deterministically)"""
    if t.startswith("struct") or t.startswith("union"): return f"mk_{t.split()[1]}({seed})"
    if t == "_Bool": return str(seed & 1)
    if t in ("float", "double", "long double"): return f"({t})({seed % 1000} * 0.25 - 7)"
    return f"({t}){seed * 2654435761 % 4294967291}"

def show(t, e):
    """statements that fold value e of type t into the checksum h"""
    if t.startswith("struct") or t.startswith("union"): return f"h = h * 31 + hash_{t.split()[1]}(&({e}));"
    if t in ("float", "double", "long double"): return f"h = h * 31 + (unsigned long)(long)(({e}) * 16);"
    return f"h = h * 31 + (unsigned long)({e});"

common = ["/* generated by abigen.py */", "extern int printf(const char *, ...);", "#include <stdarg.h>"] + decls
helpers = []
def hash_member(t, e):
    """the value of member e (type t), never its padding: floats by their bits"""
    if t.startswith("struct") or t.startswith("union"): return f"h = h * 131 + hash_{t.split()[1]}(&{e});"
    if t == "float": return f"{{ unsigned b; __builtin_memcpy(&b, &{e}, 4); h = h * 131 + b; }}"
    if t == "double": return f"{{ unsigned long b; __builtin_memcpy(&b, &{e}, 8); h = h * 131 + b; }}"
    return f"h = h * 131 + (unsigned long)({e});"
for s_ in structs:
    n = s_.split()[1]
    helpers.append(f"static {s_} mk_{n}(int seed) {{ {s_} v; unsigned char *p = (unsigned char *)&v;")
    helpers.append(f"    for (unsigned i = 0; i < sizeof v; i++) p[i] = (unsigned char)(seed * 7 + i * 13); return v; }}")
    body = []
    for t, m, a in members[s_]:
        if a: body.append(f"for (int i = 0; i < {a}; i++) {hash_member(t, f'v->{m}[i]')}")
        else: body.append(hash_member(t, f"v->{m}"))
    helpers.append(f"static unsigned long hash_{n}(const {s_} *v) {{ unsigned long h = 0; " + " ".join(body) + " return h; }")
# fill only the bytes of members: padding may differ, so hash member-wise after a copy through mk (bytes set by mk are all defined)
cases = []
for c in range(ncase):
    nargs = random.randint(1, 12)
    args = [random.choice(SCAL + structs + structs) for _ in range(nargs)]
    ret = random.choice(SCAL + structs + ["void"])
    var = random.random() < 0.2
    cases.append((args, ret, var))
callee, caller = [], []
for c, (args, ret, var) in enumerate(cases):
    params = ", ".join(f"{t} a{i}" for i, t in enumerate(args)) + (", ..." if var else "")
    proto = f"{ret} f{c}({params})"
    callee.append(proto + " {")
    callee.append("    unsigned long h = 0;")
    for i, t in enumerate(args): callee.append("    " + show(t, f"a{i}"))
    if var:
        callee.append("    va_list ap; va_start(ap, a%d);" % (len(args) - 1))
        callee.append("    for (int k = 0; k < 3; k++) { h = h * 31 + (unsigned long)va_arg(ap, long); h = h * 31 + (unsigned long)(long)(va_arg(ap, double) * 4); }")
        callee.append(f"    {{ {structs[0]} s = va_arg(ap, {structs[0]}); h = h * 31 + hash_S0(&s); }} va_end(ap);")
    callee.append(f'    printf("f{c} %lx\\n", h);')
    if ret != "void":
        if ret.startswith("struct") or ret.startswith("union"): callee.append(f"    {ret} r = mk_{ret.split()[1]}((int)h); return r;")
        else: callee.append(f"    return {val(ret, 'h')};".replace("h * 2654435761", "h") if False else f"    return ({ret})(h % 1000);")
    callee.append("}")
    caller.append(proto + ";")
for c, (args, ret, var) in enumerate(cases):
    actual = ", ".join(val(t, c * 17 + i) for i, t in enumerate(args))
    if var: actual += ", 11L, 2.5, -3L, -1.25, 1L << 40, 1e3, mk_S0(5)"
    caller.append(f"static void call{c}(void) {{ unsigned long h = 0;")
    if ret == "void": caller.append(f"    f{c}({actual});")
    else: caller.append(f"    {ret} r = f{c}({actual}); " + show(ret, "r"))
    caller.append(f'    printf("r{c} %lx\\n", h); }}')
caller.append("int main(void) {")
caller += [f"    call{c}();" for c in range(ncase)]
caller.append("    return 0; }")
open(f"{out}/callee.c", "w").write("\n".join(common + helpers + callee) + "\n")
open(f"{out}/caller.c", "w").write("\n".join(common + helpers + caller) + "\n")
def run(cmd):
    r = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if r.returncode: sys.exit(f"abi: failed: {cmd}\n{r.stderr[:2000]}")
    return r.stdout
G = "gcc -w -O1 -fno-strict-aliasing"
run(f"{G} -c -o {out}/callee.g.o {out}/callee.c && {G} -c -o {out}/caller.g.o {out}/caller.c")
run(f"{sicc} -c -o {out}/callee.s.o {out}/callee.c && {sicc} -c -o {out}/caller.s.o {out}/caller.c")
want = run(f"gcc -no-pie -o {out}/gg {out}/caller.g.o {out}/callee.g.o && {out}/gg")
bad = 0
for name, objs in (("sicc callee", "caller.g.o callee.s.o"), ("sicc caller", "caller.s.o callee.g.o"), ("sicc both", "caller.s.o callee.s.o")):
    got = run(f"cd {out} && gcc -no-pie -o x {objs} && ./x")
    if got != want:
        bad += 1
        w, g = want.splitlines(), got.splitlines()
        first = next((i for i in range(min(len(w), len(g))) if w[i] != g[i]), min(len(w), len(g)))
        print(f"abi: {name}: differs at line {first + 1}: want {w[first] if first < len(w) else '-'}, got {g[first] if first < len(g) else '-'}")
print(f"sicc abi: {ncase} signatures, {3 - bad} of 3 combinations agree")
sys.exit(1 if bad else 0)
