#!/usr/bin/env python3
"""
signames.py CC OUT - dash's signames.c for the target: its mksignames runs
on the build machine and would record the build machine's signal numbers,
so the table is made from the target's <signal.h>, through CC's
preprocessor.
"""
import re
import subprocess
import sys

NAMES = ['HUP', 'INT', 'QUIT', 'ILL', 'TRAP', 'ABRT', 'EMT', 'FPE', 'KILL', 'BUS', 'SEGV', 'SYS',
         'PIPE', 'ALRM', 'TERM', 'USR1', 'USR2', 'CHLD', 'PWR', 'WINCH', 'URG', 'POLL', 'STOP',
         'TSTP', 'CONT', 'TTIN', 'TTOU', 'VTALRM', 'PROF', 'XCPU', 'XFSZ', 'WAITING', 'LWP',
         'FREEZE', 'THAW', 'CANCEL', 'LOST', 'XRES', 'JVM1', 'JVM2', 'INFO']

def main():
    cc, out = sys.argv[1], sys.argv[2]
    src = '#define _GNU_SOURCE\n#include <signal.h>\n' + ''.join(
        '@K_%s@ SIG%s\n' % (n, n) for n in NAMES) + '@K_NSIG@ _NSIG\n'
    pp = subprocess.run([cc, '-E', '-P', '-x', 'c', '-'], input=src, capture_output=True, text=True,
                        check=True).stdout
    val = {}
    for m in re.finditer(r'@K_(\w+)@\s+\(?\s*(\d+)\s*\)?', pp):
        val[m.group(1)] = int(m.group(2))
    nsig = val.pop('NSIG')
    table = [str(i) for i in range(nsig)]              # 0 .. NSIG-1, then the terminating null
    table[0] = 'EXIT'
    for n in NAMES:
        if n in val and 0 < val[n] < nsig and table[val[n]] == str(val[n]):
            table[val[n]] = n
    with open(out, 'w') as f:
        f.write('/* generated by ports/signames.py from the target <signal.h> */\n\n'
                '#include <signal.h>\n\nconst char *const signal_names[NSIG + 1] = {\n')
        for name in table:
            f.write('    "%s",\n' % name)
        f.write('    (char *)0x0\n};\n')

if __name__ == '__main__':
    main()
