/* arm_neon.h - NEON intrinsics for sicc on AArch64 (generated by
 * tools/cc/mkneon.py: do not edit). Each function is one vector operator or
 * one __builtin_neon(operation, (result type *)0, a, b, accumulator, imm),
 * which becomes one NEON instruction. Vectors are values like structs; the
 * functions are always inlined. float16x4_t/float16x8_t hold half-precision
 * bits (unsigned short): vcvt_f32_f16 and vcvt_f16_f32 convert them.
 * The dot product (vdotq_s32...) needs -march=armv8.2-a+dotprod.
 * Part of SIEOS. SPDX-License-Identifier: GPL-3.0-only */
#ifndef _ARM_NEON_H
#define _ARM_NEON_H
#ifndef __aarch64__
#error "arm_neon.h: AArch64 only"
#endif

enum { __NOP_ADD, __NOP_SUB, __NOP_MUL, __NOP_DIV, __NOP_AND, __NOP_OR, __NOP_XOR, __NOP_SHL, __NOP_SHR, __NOP_NEG, __NOP_NOT, __NOP_EQ, __NOP_NE, __NOP_LT, __NOP_LE, __NOP_GT, __NOP_GE, __NOP_SHLI, __NOP_SHRI, __NOP_SARI, __NOP_MIN, __NOP_MAX, __NOP_SQRT, __NOP_ANDNOT, __NOP_UNPCKLO, __NOP_UNPCKHI, __NOP_CVTI2F, __NOP_CVTF2I, __NOP_MADD, __NOP_MADDUBS, __NOP_AVG, __NOP_ADDS, __NOP_SUBS, __NOP_PACKS, __NOP_PACKUS, __NOP_MULHI, __NOP_MULUDQ, __NOP_SAD, __NOP_SHUFB, __NOP_MOVEMASK, __NOP_SPLAT, __NOP_SHUF, __NOP_CVTF2IR, __NOP_SLLDQ, __NOP_SRLDQ, __NOP_PSHUFD, __NOP_ABS, __NOP_MOD, __NOP_FMA, __NOP_FMS, __NOP_MLA, __NOP_MLS, __NOP_DOT, __NOP_DOTL, __NOP_MULL, __NOP_MULL2, __NOP_MLAL, __NOP_MLAL2, __NOP_PADDL, __NOP_PADAL, __NOP_ADDP, __NOP_ADDV, __NOP_MOVL, __NOP_MOVL2, __NOP_XTN, __NOP_QXTN, __NOP_QXTUN, __NOP_UZP1, __NOP_UZP2, __NOP_TRN1, __NOP_TRN2, __NOP_EXT, __NOP_DUPL, __NOP_TBL, __NOP_CNT, __NOP_BSL, __NOP_FCVTL, __NOP_FCVTL2, __NOP_FCVTN };
void *memcpy(void *, const void *, __SIZE_TYPE__);  /* (small and constant: inlined) */
#define __SI static __inline__ __attribute__((always_inline))
#define __N(op, T, a, b, c, i) __builtin_neon(__NOP_##op, (T *)0, a, b, c, i)
#define __V(op, a, b) __builtin_vec(__NOP_##op, a, b, 0)

typedef signed char int8x8_t __attribute__((vector_size(8)));
typedef signed char int8x16_t __attribute__((vector_size(16)));
typedef unsigned char uint8x8_t __attribute__((vector_size(8)));
typedef unsigned char uint8x16_t __attribute__((vector_size(16)));
typedef short int16x4_t __attribute__((vector_size(8)));
typedef short int16x8_t __attribute__((vector_size(16)));
typedef unsigned short uint16x4_t __attribute__((vector_size(8)));
typedef unsigned short uint16x8_t __attribute__((vector_size(16)));
typedef int int32x2_t __attribute__((vector_size(8)));
typedef int int32x4_t __attribute__((vector_size(16)));
typedef unsigned uint32x2_t __attribute__((vector_size(8)));
typedef unsigned uint32x4_t __attribute__((vector_size(16)));
typedef long int64x1_t __attribute__((vector_size(8)));
typedef long int64x2_t __attribute__((vector_size(16)));
typedef unsigned long uint64x1_t __attribute__((vector_size(8)));
typedef unsigned long uint64x2_t __attribute__((vector_size(16)));
typedef float float32x2_t __attribute__((vector_size(8)));
typedef float float32x4_t __attribute__((vector_size(16)));
typedef double float64x1_t __attribute__((vector_size(8)));
typedef double float64x2_t __attribute__((vector_size(16)));
typedef unsigned short float16x4_t __attribute__((vector_size(8)));
typedef unsigned short float16x8_t __attribute__((vector_size(16)));

/* int8x8_t */
__SI int8x8_t vld1_s8(const signed char *p) { int8x8_t r; memcpy(&r, p, 8); return r; }
__SI void vst1_s8(signed char *p, int8x8_t a) { memcpy(p, &a, 8); }
__SI int8x8_t vdup_n_s8(signed char x) { return __N(SPLAT, int8x8_t, x, 0, 0, 0); }
__SI int8x8_t vmov_n_s8(signed char x) { return vdup_n_s8(x); }
__SI int8x8_t vld1_dup_s8(const signed char *p) { return vdup_n_s8(*p); }
__SI int8x8_t vadd_s8(int8x8_t a, int8x8_t b) { return a + b; }
__SI int8x8_t vsub_s8(int8x8_t a, int8x8_t b) { return a - b; }
__SI int8x8_t vmul_s8(int8x8_t a, int8x8_t b) { return a * b; }
__SI uint8x8_t vceq_s8(int8x8_t a, int8x8_t b) { return (uint8x8_t)(a == b); }
__SI uint8x8_t vcgt_s8(int8x8_t a, int8x8_t b) { return (uint8x8_t)(a > b); }
__SI uint8x8_t vcge_s8(int8x8_t a, int8x8_t b) { return (uint8x8_t)(a >= b); }
__SI uint8x8_t vclt_s8(int8x8_t a, int8x8_t b) { return (uint8x8_t)(a < b); }
__SI uint8x8_t vcle_s8(int8x8_t a, int8x8_t b) { return (uint8x8_t)(a <= b); }
__SI int8x8_t vbsl_s8(uint8x8_t m, int8x8_t a, int8x8_t b) { return __N(BSL, int8x8_t, a, b, (int8x8_t)m, 0); }
__SI int8x8_t vzip1_s8(int8x8_t a, int8x8_t b) { return __V(UNPCKLO, a, b); }
__SI int8x8_t vzip2_s8(int8x8_t a, int8x8_t b) { return __V(UNPCKHI, a, b); }
__SI int8x8_t vuzp1_s8(int8x8_t a, int8x8_t b) { return __N(UZP1, int8x8_t, a, b, 0, 0); }
__SI int8x8_t vuzp2_s8(int8x8_t a, int8x8_t b) { return __N(UZP2, int8x8_t, a, b, 0, 0); }
__SI int8x8_t vtrn1_s8(int8x8_t a, int8x8_t b) { return __N(TRN1, int8x8_t, a, b, 0, 0); }
__SI int8x8_t vtrn2_s8(int8x8_t a, int8x8_t b) { return __N(TRN2, int8x8_t, a, b, 0, 0); }
#define vext_s8(a, b, n) __N(EXT, int8x8_t, (int8x8_t)(a), (int8x8_t)(b), 0, (n) * 1)
#define vget_lane_s8(a, n) (((int8x8_t)(a))[n])
#define vset_lane_s8(x, a, n) ({ int8x8_t __t = (a); __t[n] = (x); __t; })
#define vdup_lane_s8(a, n) __N(DUPL, int8x8_t, (int8x8_t)(a), 0, 0, n)
__SI int8x8_t vpadd_s8(int8x8_t a, int8x8_t b) { return __N(ADDP, int8x8_t, a, b, 0, 0); }
__SI signed char vaddv_s8(int8x8_t a) { return __N(ADDV, signed char, a, 0, 0, 0); }
__SI int8x8_t vand_s8(int8x8_t a, int8x8_t b) { return a & b; }
__SI int8x8_t vorr_s8(int8x8_t a, int8x8_t b) { return a | b; }
__SI int8x8_t veor_s8(int8x8_t a, int8x8_t b) { return a ^ b; }
__SI int8x8_t vbic_s8(int8x8_t a, int8x8_t b) { return __V(ANDNOT, b, a); }
__SI int8x8_t vmvn_s8(int8x8_t a) { return ~a; }
#define vshl_n_s8(a, n) ((int8x8_t)(a) << (n))
#define vshr_n_s8(a, n) ((int8x8_t)(a) >> (n))
__SI int8x8_t vshl_s8(int8x8_t a, int8x8_t b) { return __V(SHL, a, (int8x8_t)b); }
__SI int8x8_t vqadd_s8(int8x8_t a, int8x8_t b) { return __V(ADDS, a, b); }
__SI int8x8_t vqsub_s8(int8x8_t a, int8x8_t b) { return __V(SUBS, a, b); }
__SI int8x8_t vneg_s8(int8x8_t a) { return -a; }
__SI int8x8_t vabs_s8(int8x8_t a) { return __V(ABS, a, a); }
__SI int8x8_t vmax_s8(int8x8_t a, int8x8_t b) { return __V(MAX, a, b); }
__SI int8x8_t vmin_s8(int8x8_t a, int8x8_t b) { return __V(MIN, a, b); }
__SI int8x8_t vrhadd_s8(int8x8_t a, int8x8_t b) { return __V(AVG, a, b); }
__SI int8x8_t vmla_s8(int8x8_t a, int8x8_t b, int8x8_t c) { return __N(MLA, int8x8_t, b, c, a, 0); }
__SI int8x8_t vmls_s8(int8x8_t a, int8x8_t b, int8x8_t c) { return __N(MLS, int8x8_t, b, c, a, 0); }
__SI int8x8_t vcnt_s8(int8x8_t a) { return __N(CNT, int8x8_t, a, 0, 0, 0); }
__SI int16x4_t vpaddl_s8(int8x8_t a) { return __N(PADDL, int16x4_t, a, 0, 0, 0); }
__SI int16x4_t vpadal_s8(int16x4_t acc, int8x8_t a) { return __N(PADAL, int16x4_t, a, 0, acc, 0); }

/* int8x16_t */
__SI int8x16_t vld1q_s8(const signed char *p) { int8x16_t r; memcpy(&r, p, 16); return r; }
__SI void vst1q_s8(signed char *p, int8x16_t a) { memcpy(p, &a, 16); }
__SI int8x16_t vdupq_n_s8(signed char x) { return __N(SPLAT, int8x16_t, x, 0, 0, 0); }
__SI int8x16_t vmovq_n_s8(signed char x) { return vdupq_n_s8(x); }
__SI int8x16_t vld1q_dup_s8(const signed char *p) { return vdupq_n_s8(*p); }
__SI int8x16_t vaddq_s8(int8x16_t a, int8x16_t b) { return a + b; }
__SI int8x16_t vsubq_s8(int8x16_t a, int8x16_t b) { return a - b; }
__SI int8x16_t vmulq_s8(int8x16_t a, int8x16_t b) { return a * b; }
__SI uint8x16_t vceqq_s8(int8x16_t a, int8x16_t b) { return (uint8x16_t)(a == b); }
__SI uint8x16_t vcgtq_s8(int8x16_t a, int8x16_t b) { return (uint8x16_t)(a > b); }
__SI uint8x16_t vcgeq_s8(int8x16_t a, int8x16_t b) { return (uint8x16_t)(a >= b); }
__SI uint8x16_t vcltq_s8(int8x16_t a, int8x16_t b) { return (uint8x16_t)(a < b); }
__SI uint8x16_t vcleq_s8(int8x16_t a, int8x16_t b) { return (uint8x16_t)(a <= b); }
__SI int8x16_t vbslq_s8(uint8x16_t m, int8x16_t a, int8x16_t b) { return __N(BSL, int8x16_t, a, b, (int8x16_t)m, 0); }
__SI int8x16_t vzip1q_s8(int8x16_t a, int8x16_t b) { return __V(UNPCKLO, a, b); }
__SI int8x16_t vzip2q_s8(int8x16_t a, int8x16_t b) { return __V(UNPCKHI, a, b); }
__SI int8x16_t vuzp1q_s8(int8x16_t a, int8x16_t b) { return __N(UZP1, int8x16_t, a, b, 0, 0); }
__SI int8x16_t vuzp2q_s8(int8x16_t a, int8x16_t b) { return __N(UZP2, int8x16_t, a, b, 0, 0); }
__SI int8x16_t vtrn1q_s8(int8x16_t a, int8x16_t b) { return __N(TRN1, int8x16_t, a, b, 0, 0); }
__SI int8x16_t vtrn2q_s8(int8x16_t a, int8x16_t b) { return __N(TRN2, int8x16_t, a, b, 0, 0); }
#define vextq_s8(a, b, n) __N(EXT, int8x16_t, (int8x16_t)(a), (int8x16_t)(b), 0, (n) * 1)
#define vgetq_lane_s8(a, n) (((int8x16_t)(a))[n])
#define vsetq_lane_s8(x, a, n) ({ int8x16_t __t = (a); __t[n] = (x); __t; })
#define vdupq_laneq_s8(a, n) __N(DUPL, int8x16_t, (int8x16_t)(a), 0, 0, n)
__SI int8x16_t vpaddq_s8(int8x16_t a, int8x16_t b) { return __N(ADDP, int8x16_t, a, b, 0, 0); }
__SI signed char vaddvq_s8(int8x16_t a) { return __N(ADDV, signed char, a, 0, 0, 0); }
__SI int8x16_t vandq_s8(int8x16_t a, int8x16_t b) { return a & b; }
__SI int8x16_t vorrq_s8(int8x16_t a, int8x16_t b) { return a | b; }
__SI int8x16_t veorq_s8(int8x16_t a, int8x16_t b) { return a ^ b; }
__SI int8x16_t vbicq_s8(int8x16_t a, int8x16_t b) { return __V(ANDNOT, b, a); }
__SI int8x16_t vmvnq_s8(int8x16_t a) { return ~a; }
#define vshlq_n_s8(a, n) ((int8x16_t)(a) << (n))
#define vshrq_n_s8(a, n) ((int8x16_t)(a) >> (n))
__SI int8x16_t vshlq_s8(int8x16_t a, int8x16_t b) { return __V(SHL, a, (int8x16_t)b); }
__SI int8x16_t vqaddq_s8(int8x16_t a, int8x16_t b) { return __V(ADDS, a, b); }
__SI int8x16_t vqsubq_s8(int8x16_t a, int8x16_t b) { return __V(SUBS, a, b); }
__SI int8x16_t vnegq_s8(int8x16_t a) { return -a; }
__SI int8x16_t vabsq_s8(int8x16_t a) { return __V(ABS, a, a); }
__SI int8x16_t vmaxq_s8(int8x16_t a, int8x16_t b) { return __V(MAX, a, b); }
__SI int8x16_t vminq_s8(int8x16_t a, int8x16_t b) { return __V(MIN, a, b); }
__SI int8x16_t vrhaddq_s8(int8x16_t a, int8x16_t b) { return __V(AVG, a, b); }
__SI int8x16_t vmlaq_s8(int8x16_t a, int8x16_t b, int8x16_t c) { return __N(MLA, int8x16_t, b, c, a, 0); }
__SI int8x16_t vmlsq_s8(int8x16_t a, int8x16_t b, int8x16_t c) { return __N(MLS, int8x16_t, b, c, a, 0); }
__SI int8x16_t vcntq_s8(int8x16_t a) { return __N(CNT, int8x16_t, a, 0, 0, 0); }
__SI int16x8_t vpaddlq_s8(int8x16_t a) { return __N(PADDL, int16x8_t, a, 0, 0, 0); }
__SI int16x8_t vpadalq_s8(int16x8_t acc, int8x16_t a) { return __N(PADAL, int16x8_t, a, 0, acc, 0); }

__SI int16x8_t vmull_s8(int8x8_t a, int8x8_t b) { return __N(MULL, int16x8_t, a, b, 0, 0); }
__SI int16x8_t vmull_high_s8(int8x16_t a, int8x16_t b) { return __N(MULL2, int16x8_t, a, b, 0, 0); }
__SI int16x8_t vmlal_s8(int16x8_t acc, int8x8_t a, int8x8_t b) { return __N(MLAL, int16x8_t, a, b, acc, 0); }
__SI int16x8_t vmlal_high_s8(int16x8_t acc, int8x16_t a, int8x16_t b) { return __N(MLAL2, int16x8_t, a, b, acc, 0); }
__SI int16x8_t vmovl_s8(int8x8_t a) { return __N(MOVL, int16x8_t, a, 0, 0, 0); }
__SI int16x8_t vmovl_high_s8(int8x16_t a) { return __N(MOVL2, int16x8_t, a, 0, 0, 0); }
__SI int8x8_t vget_low_s8(int8x16_t a) { int8x8_t r; memcpy(&r, &a, 8); return r; }
__SI int8x8_t vget_high_s8(int8x16_t a) { int8x8_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
__SI int8x16_t vcombine_s8(int8x8_t lo, int8x8_t hi) { int8x16_t r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }

/* uint8x8_t */
__SI uint8x8_t vld1_u8(const unsigned char *p) { uint8x8_t r; memcpy(&r, p, 8); return r; }
__SI void vst1_u8(unsigned char *p, uint8x8_t a) { memcpy(p, &a, 8); }
__SI uint8x8_t vdup_n_u8(unsigned char x) { return __N(SPLAT, uint8x8_t, x, 0, 0, 0); }
__SI uint8x8_t vmov_n_u8(unsigned char x) { return vdup_n_u8(x); }
__SI uint8x8_t vld1_dup_u8(const unsigned char *p) { return vdup_n_u8(*p); }
__SI uint8x8_t vadd_u8(uint8x8_t a, uint8x8_t b) { return a + b; }
__SI uint8x8_t vsub_u8(uint8x8_t a, uint8x8_t b) { return a - b; }
__SI uint8x8_t vmul_u8(uint8x8_t a, uint8x8_t b) { return a * b; }
__SI uint8x8_t vceq_u8(uint8x8_t a, uint8x8_t b) { return (uint8x8_t)(a == b); }
__SI uint8x8_t vcgt_u8(uint8x8_t a, uint8x8_t b) { return (uint8x8_t)(a > b); }
__SI uint8x8_t vcge_u8(uint8x8_t a, uint8x8_t b) { return (uint8x8_t)(a >= b); }
__SI uint8x8_t vclt_u8(uint8x8_t a, uint8x8_t b) { return (uint8x8_t)(a < b); }
__SI uint8x8_t vcle_u8(uint8x8_t a, uint8x8_t b) { return (uint8x8_t)(a <= b); }
__SI uint8x8_t vbsl_u8(uint8x8_t m, uint8x8_t a, uint8x8_t b) { return __N(BSL, uint8x8_t, a, b, (uint8x8_t)m, 0); }
__SI uint8x8_t vzip1_u8(uint8x8_t a, uint8x8_t b) { return __V(UNPCKLO, a, b); }
__SI uint8x8_t vzip2_u8(uint8x8_t a, uint8x8_t b) { return __V(UNPCKHI, a, b); }
__SI uint8x8_t vuzp1_u8(uint8x8_t a, uint8x8_t b) { return __N(UZP1, uint8x8_t, a, b, 0, 0); }
__SI uint8x8_t vuzp2_u8(uint8x8_t a, uint8x8_t b) { return __N(UZP2, uint8x8_t, a, b, 0, 0); }
__SI uint8x8_t vtrn1_u8(uint8x8_t a, uint8x8_t b) { return __N(TRN1, uint8x8_t, a, b, 0, 0); }
__SI uint8x8_t vtrn2_u8(uint8x8_t a, uint8x8_t b) { return __N(TRN2, uint8x8_t, a, b, 0, 0); }
#define vext_u8(a, b, n) __N(EXT, uint8x8_t, (uint8x8_t)(a), (uint8x8_t)(b), 0, (n) * 1)
#define vget_lane_u8(a, n) (((uint8x8_t)(a))[n])
#define vset_lane_u8(x, a, n) ({ uint8x8_t __t = (a); __t[n] = (x); __t; })
#define vdup_lane_u8(a, n) __N(DUPL, uint8x8_t, (uint8x8_t)(a), 0, 0, n)
__SI uint8x8_t vpadd_u8(uint8x8_t a, uint8x8_t b) { return __N(ADDP, uint8x8_t, a, b, 0, 0); }
__SI unsigned char vaddv_u8(uint8x8_t a) { return __N(ADDV, unsigned char, a, 0, 0, 0); }
__SI uint8x8_t vand_u8(uint8x8_t a, uint8x8_t b) { return a & b; }
__SI uint8x8_t vorr_u8(uint8x8_t a, uint8x8_t b) { return a | b; }
__SI uint8x8_t veor_u8(uint8x8_t a, uint8x8_t b) { return a ^ b; }
__SI uint8x8_t vbic_u8(uint8x8_t a, uint8x8_t b) { return __V(ANDNOT, b, a); }
__SI uint8x8_t vmvn_u8(uint8x8_t a) { return ~a; }
#define vshl_n_u8(a, n) ((uint8x8_t)(a) << (n))
#define vshr_n_u8(a, n) ((uint8x8_t)(a) >> (n))
__SI uint8x8_t vshl_u8(uint8x8_t a, int8x8_t b) { return __V(SHL, a, (uint8x8_t)b); }
__SI uint8x8_t vqadd_u8(uint8x8_t a, uint8x8_t b) { return __V(ADDS, a, b); }
__SI uint8x8_t vqsub_u8(uint8x8_t a, uint8x8_t b) { return __V(SUBS, a, b); }
__SI uint8x8_t vmax_u8(uint8x8_t a, uint8x8_t b) { return __V(MAX, a, b); }
__SI uint8x8_t vmin_u8(uint8x8_t a, uint8x8_t b) { return __V(MIN, a, b); }
__SI uint8x8_t vrhadd_u8(uint8x8_t a, uint8x8_t b) { return __V(AVG, a, b); }
__SI uint8x8_t vmla_u8(uint8x8_t a, uint8x8_t b, uint8x8_t c) { return __N(MLA, uint8x8_t, b, c, a, 0); }
__SI uint8x8_t vmls_u8(uint8x8_t a, uint8x8_t b, uint8x8_t c) { return __N(MLS, uint8x8_t, b, c, a, 0); }
__SI uint8x8_t vcnt_u8(uint8x8_t a) { return __N(CNT, uint8x8_t, a, 0, 0, 0); }
__SI uint16x4_t vpaddl_u8(uint8x8_t a) { return __N(PADDL, uint16x4_t, a, 0, 0, 0); }
__SI uint16x4_t vpadal_u8(uint16x4_t acc, uint8x8_t a) { return __N(PADAL, uint16x4_t, a, 0, acc, 0); }

/* uint8x16_t */
__SI uint8x16_t vld1q_u8(const unsigned char *p) { uint8x16_t r; memcpy(&r, p, 16); return r; }
__SI void vst1q_u8(unsigned char *p, uint8x16_t a) { memcpy(p, &a, 16); }
__SI uint8x16_t vdupq_n_u8(unsigned char x) { return __N(SPLAT, uint8x16_t, x, 0, 0, 0); }
__SI uint8x16_t vmovq_n_u8(unsigned char x) { return vdupq_n_u8(x); }
__SI uint8x16_t vld1q_dup_u8(const unsigned char *p) { return vdupq_n_u8(*p); }
__SI uint8x16_t vaddq_u8(uint8x16_t a, uint8x16_t b) { return a + b; }
__SI uint8x16_t vsubq_u8(uint8x16_t a, uint8x16_t b) { return a - b; }
__SI uint8x16_t vmulq_u8(uint8x16_t a, uint8x16_t b) { return a * b; }
__SI uint8x16_t vceqq_u8(uint8x16_t a, uint8x16_t b) { return (uint8x16_t)(a == b); }
__SI uint8x16_t vcgtq_u8(uint8x16_t a, uint8x16_t b) { return (uint8x16_t)(a > b); }
__SI uint8x16_t vcgeq_u8(uint8x16_t a, uint8x16_t b) { return (uint8x16_t)(a >= b); }
__SI uint8x16_t vcltq_u8(uint8x16_t a, uint8x16_t b) { return (uint8x16_t)(a < b); }
__SI uint8x16_t vcleq_u8(uint8x16_t a, uint8x16_t b) { return (uint8x16_t)(a <= b); }
__SI uint8x16_t vbslq_u8(uint8x16_t m, uint8x16_t a, uint8x16_t b) { return __N(BSL, uint8x16_t, a, b, (uint8x16_t)m, 0); }
__SI uint8x16_t vzip1q_u8(uint8x16_t a, uint8x16_t b) { return __V(UNPCKLO, a, b); }
__SI uint8x16_t vzip2q_u8(uint8x16_t a, uint8x16_t b) { return __V(UNPCKHI, a, b); }
__SI uint8x16_t vuzp1q_u8(uint8x16_t a, uint8x16_t b) { return __N(UZP1, uint8x16_t, a, b, 0, 0); }
__SI uint8x16_t vuzp2q_u8(uint8x16_t a, uint8x16_t b) { return __N(UZP2, uint8x16_t, a, b, 0, 0); }
__SI uint8x16_t vtrn1q_u8(uint8x16_t a, uint8x16_t b) { return __N(TRN1, uint8x16_t, a, b, 0, 0); }
__SI uint8x16_t vtrn2q_u8(uint8x16_t a, uint8x16_t b) { return __N(TRN2, uint8x16_t, a, b, 0, 0); }
#define vextq_u8(a, b, n) __N(EXT, uint8x16_t, (uint8x16_t)(a), (uint8x16_t)(b), 0, (n) * 1)
#define vgetq_lane_u8(a, n) (((uint8x16_t)(a))[n])
#define vsetq_lane_u8(x, a, n) ({ uint8x16_t __t = (a); __t[n] = (x); __t; })
#define vdupq_laneq_u8(a, n) __N(DUPL, uint8x16_t, (uint8x16_t)(a), 0, 0, n)
__SI uint8x16_t vpaddq_u8(uint8x16_t a, uint8x16_t b) { return __N(ADDP, uint8x16_t, a, b, 0, 0); }
__SI unsigned char vaddvq_u8(uint8x16_t a) { return __N(ADDV, unsigned char, a, 0, 0, 0); }
__SI uint8x16_t vandq_u8(uint8x16_t a, uint8x16_t b) { return a & b; }
__SI uint8x16_t vorrq_u8(uint8x16_t a, uint8x16_t b) { return a | b; }
__SI uint8x16_t veorq_u8(uint8x16_t a, uint8x16_t b) { return a ^ b; }
__SI uint8x16_t vbicq_u8(uint8x16_t a, uint8x16_t b) { return __V(ANDNOT, b, a); }
__SI uint8x16_t vmvnq_u8(uint8x16_t a) { return ~a; }
#define vshlq_n_u8(a, n) ((uint8x16_t)(a) << (n))
#define vshrq_n_u8(a, n) ((uint8x16_t)(a) >> (n))
__SI uint8x16_t vshlq_u8(uint8x16_t a, int8x16_t b) { return __V(SHL, a, (uint8x16_t)b); }
__SI uint8x16_t vqaddq_u8(uint8x16_t a, uint8x16_t b) { return __V(ADDS, a, b); }
__SI uint8x16_t vqsubq_u8(uint8x16_t a, uint8x16_t b) { return __V(SUBS, a, b); }
__SI uint8x16_t vmaxq_u8(uint8x16_t a, uint8x16_t b) { return __V(MAX, a, b); }
__SI uint8x16_t vminq_u8(uint8x16_t a, uint8x16_t b) { return __V(MIN, a, b); }
__SI uint8x16_t vrhaddq_u8(uint8x16_t a, uint8x16_t b) { return __V(AVG, a, b); }
__SI uint8x16_t vmlaq_u8(uint8x16_t a, uint8x16_t b, uint8x16_t c) { return __N(MLA, uint8x16_t, b, c, a, 0); }
__SI uint8x16_t vmlsq_u8(uint8x16_t a, uint8x16_t b, uint8x16_t c) { return __N(MLS, uint8x16_t, b, c, a, 0); }
__SI uint8x16_t vcntq_u8(uint8x16_t a) { return __N(CNT, uint8x16_t, a, 0, 0, 0); }
__SI uint16x8_t vpaddlq_u8(uint8x16_t a) { return __N(PADDL, uint16x8_t, a, 0, 0, 0); }
__SI uint16x8_t vpadalq_u8(uint16x8_t acc, uint8x16_t a) { return __N(PADAL, uint16x8_t, a, 0, acc, 0); }

__SI uint16x8_t vmull_u8(uint8x8_t a, uint8x8_t b) { return __N(MULL, uint16x8_t, a, b, 0, 0); }
__SI uint16x8_t vmull_high_u8(uint8x16_t a, uint8x16_t b) { return __N(MULL2, uint16x8_t, a, b, 0, 0); }
__SI uint16x8_t vmlal_u8(uint16x8_t acc, uint8x8_t a, uint8x8_t b) { return __N(MLAL, uint16x8_t, a, b, acc, 0); }
__SI uint16x8_t vmlal_high_u8(uint16x8_t acc, uint8x16_t a, uint8x16_t b) { return __N(MLAL2, uint16x8_t, a, b, acc, 0); }
__SI uint16x8_t vmovl_u8(uint8x8_t a) { return __N(MOVL, uint16x8_t, a, 0, 0, 0); }
__SI uint16x8_t vmovl_high_u8(uint8x16_t a) { return __N(MOVL2, uint16x8_t, a, 0, 0, 0); }
__SI uint8x8_t vget_low_u8(uint8x16_t a) { uint8x8_t r; memcpy(&r, &a, 8); return r; }
__SI uint8x8_t vget_high_u8(uint8x16_t a) { uint8x8_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
__SI uint8x16_t vcombine_u8(uint8x8_t lo, uint8x8_t hi) { uint8x16_t r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }

/* int16x4_t */
__SI int16x4_t vld1_s16(const short *p) { int16x4_t r; memcpy(&r, p, 8); return r; }
__SI void vst1_s16(short *p, int16x4_t a) { memcpy(p, &a, 8); }
__SI int16x4_t vdup_n_s16(short x) { return __N(SPLAT, int16x4_t, x, 0, 0, 0); }
__SI int16x4_t vmov_n_s16(short x) { return vdup_n_s16(x); }
__SI int16x4_t vld1_dup_s16(const short *p) { return vdup_n_s16(*p); }
__SI int16x4_t vadd_s16(int16x4_t a, int16x4_t b) { return a + b; }
__SI int16x4_t vsub_s16(int16x4_t a, int16x4_t b) { return a - b; }
__SI int16x4_t vmul_s16(int16x4_t a, int16x4_t b) { return a * b; }
__SI uint16x4_t vceq_s16(int16x4_t a, int16x4_t b) { return (uint16x4_t)(a == b); }
__SI uint16x4_t vcgt_s16(int16x4_t a, int16x4_t b) { return (uint16x4_t)(a > b); }
__SI uint16x4_t vcge_s16(int16x4_t a, int16x4_t b) { return (uint16x4_t)(a >= b); }
__SI uint16x4_t vclt_s16(int16x4_t a, int16x4_t b) { return (uint16x4_t)(a < b); }
__SI uint16x4_t vcle_s16(int16x4_t a, int16x4_t b) { return (uint16x4_t)(a <= b); }
__SI int16x4_t vbsl_s16(uint16x4_t m, int16x4_t a, int16x4_t b) { return __N(BSL, int16x4_t, a, b, (int16x4_t)m, 0); }
__SI int16x4_t vzip1_s16(int16x4_t a, int16x4_t b) { return __V(UNPCKLO, a, b); }
__SI int16x4_t vzip2_s16(int16x4_t a, int16x4_t b) { return __V(UNPCKHI, a, b); }
__SI int16x4_t vuzp1_s16(int16x4_t a, int16x4_t b) { return __N(UZP1, int16x4_t, a, b, 0, 0); }
__SI int16x4_t vuzp2_s16(int16x4_t a, int16x4_t b) { return __N(UZP2, int16x4_t, a, b, 0, 0); }
__SI int16x4_t vtrn1_s16(int16x4_t a, int16x4_t b) { return __N(TRN1, int16x4_t, a, b, 0, 0); }
__SI int16x4_t vtrn2_s16(int16x4_t a, int16x4_t b) { return __N(TRN2, int16x4_t, a, b, 0, 0); }
#define vext_s16(a, b, n) __N(EXT, int16x4_t, (int16x4_t)(a), (int16x4_t)(b), 0, (n) * 2)
#define vget_lane_s16(a, n) (((int16x4_t)(a))[n])
#define vset_lane_s16(x, a, n) ({ int16x4_t __t = (a); __t[n] = (x); __t; })
#define vdup_lane_s16(a, n) __N(DUPL, int16x4_t, (int16x4_t)(a), 0, 0, n)
__SI int16x4_t vpadd_s16(int16x4_t a, int16x4_t b) { return __N(ADDP, int16x4_t, a, b, 0, 0); }
__SI short vaddv_s16(int16x4_t a) { return __N(ADDV, short, a, 0, 0, 0); }
__SI int16x4_t vand_s16(int16x4_t a, int16x4_t b) { return a & b; }
__SI int16x4_t vorr_s16(int16x4_t a, int16x4_t b) { return a | b; }
__SI int16x4_t veor_s16(int16x4_t a, int16x4_t b) { return a ^ b; }
__SI int16x4_t vbic_s16(int16x4_t a, int16x4_t b) { return __V(ANDNOT, b, a); }
__SI int16x4_t vmvn_s16(int16x4_t a) { return ~a; }
#define vshl_n_s16(a, n) ((int16x4_t)(a) << (n))
#define vshr_n_s16(a, n) ((int16x4_t)(a) >> (n))
__SI int16x4_t vshl_s16(int16x4_t a, int16x4_t b) { return __V(SHL, a, (int16x4_t)b); }
__SI int16x4_t vqadd_s16(int16x4_t a, int16x4_t b) { return __V(ADDS, a, b); }
__SI int16x4_t vqsub_s16(int16x4_t a, int16x4_t b) { return __V(SUBS, a, b); }
__SI int16x4_t vneg_s16(int16x4_t a) { return -a; }
__SI int16x4_t vabs_s16(int16x4_t a) { return __V(ABS, a, a); }
__SI int16x4_t vmax_s16(int16x4_t a, int16x4_t b) { return __V(MAX, a, b); }
__SI int16x4_t vmin_s16(int16x4_t a, int16x4_t b) { return __V(MIN, a, b); }
__SI int16x4_t vrhadd_s16(int16x4_t a, int16x4_t b) { return __V(AVG, a, b); }
__SI int16x4_t vmla_s16(int16x4_t a, int16x4_t b, int16x4_t c) { return __N(MLA, int16x4_t, b, c, a, 0); }
__SI int16x4_t vmls_s16(int16x4_t a, int16x4_t b, int16x4_t c) { return __N(MLS, int16x4_t, b, c, a, 0); }
__SI int32x2_t vpaddl_s16(int16x4_t a) { return __N(PADDL, int32x2_t, a, 0, 0, 0); }
__SI int32x2_t vpadal_s16(int32x2_t acc, int16x4_t a) { return __N(PADAL, int32x2_t, a, 0, acc, 0); }

/* int16x8_t */
__SI int16x8_t vld1q_s16(const short *p) { int16x8_t r; memcpy(&r, p, 16); return r; }
__SI void vst1q_s16(short *p, int16x8_t a) { memcpy(p, &a, 16); }
__SI int16x8_t vdupq_n_s16(short x) { return __N(SPLAT, int16x8_t, x, 0, 0, 0); }
__SI int16x8_t vmovq_n_s16(short x) { return vdupq_n_s16(x); }
__SI int16x8_t vld1q_dup_s16(const short *p) { return vdupq_n_s16(*p); }
__SI int16x8_t vaddq_s16(int16x8_t a, int16x8_t b) { return a + b; }
__SI int16x8_t vsubq_s16(int16x8_t a, int16x8_t b) { return a - b; }
__SI int16x8_t vmulq_s16(int16x8_t a, int16x8_t b) { return a * b; }
__SI uint16x8_t vceqq_s16(int16x8_t a, int16x8_t b) { return (uint16x8_t)(a == b); }
__SI uint16x8_t vcgtq_s16(int16x8_t a, int16x8_t b) { return (uint16x8_t)(a > b); }
__SI uint16x8_t vcgeq_s16(int16x8_t a, int16x8_t b) { return (uint16x8_t)(a >= b); }
__SI uint16x8_t vcltq_s16(int16x8_t a, int16x8_t b) { return (uint16x8_t)(a < b); }
__SI uint16x8_t vcleq_s16(int16x8_t a, int16x8_t b) { return (uint16x8_t)(a <= b); }
__SI int16x8_t vbslq_s16(uint16x8_t m, int16x8_t a, int16x8_t b) { return __N(BSL, int16x8_t, a, b, (int16x8_t)m, 0); }
__SI int16x8_t vzip1q_s16(int16x8_t a, int16x8_t b) { return __V(UNPCKLO, a, b); }
__SI int16x8_t vzip2q_s16(int16x8_t a, int16x8_t b) { return __V(UNPCKHI, a, b); }
__SI int16x8_t vuzp1q_s16(int16x8_t a, int16x8_t b) { return __N(UZP1, int16x8_t, a, b, 0, 0); }
__SI int16x8_t vuzp2q_s16(int16x8_t a, int16x8_t b) { return __N(UZP2, int16x8_t, a, b, 0, 0); }
__SI int16x8_t vtrn1q_s16(int16x8_t a, int16x8_t b) { return __N(TRN1, int16x8_t, a, b, 0, 0); }
__SI int16x8_t vtrn2q_s16(int16x8_t a, int16x8_t b) { return __N(TRN2, int16x8_t, a, b, 0, 0); }
#define vextq_s16(a, b, n) __N(EXT, int16x8_t, (int16x8_t)(a), (int16x8_t)(b), 0, (n) * 2)
#define vgetq_lane_s16(a, n) (((int16x8_t)(a))[n])
#define vsetq_lane_s16(x, a, n) ({ int16x8_t __t = (a); __t[n] = (x); __t; })
#define vdupq_laneq_s16(a, n) __N(DUPL, int16x8_t, (int16x8_t)(a), 0, 0, n)
__SI int16x8_t vpaddq_s16(int16x8_t a, int16x8_t b) { return __N(ADDP, int16x8_t, a, b, 0, 0); }
__SI short vaddvq_s16(int16x8_t a) { return __N(ADDV, short, a, 0, 0, 0); }
__SI int16x8_t vandq_s16(int16x8_t a, int16x8_t b) { return a & b; }
__SI int16x8_t vorrq_s16(int16x8_t a, int16x8_t b) { return a | b; }
__SI int16x8_t veorq_s16(int16x8_t a, int16x8_t b) { return a ^ b; }
__SI int16x8_t vbicq_s16(int16x8_t a, int16x8_t b) { return __V(ANDNOT, b, a); }
__SI int16x8_t vmvnq_s16(int16x8_t a) { return ~a; }
#define vshlq_n_s16(a, n) ((int16x8_t)(a) << (n))
#define vshrq_n_s16(a, n) ((int16x8_t)(a) >> (n))
__SI int16x8_t vshlq_s16(int16x8_t a, int16x8_t b) { return __V(SHL, a, (int16x8_t)b); }
__SI int16x8_t vqaddq_s16(int16x8_t a, int16x8_t b) { return __V(ADDS, a, b); }
__SI int16x8_t vqsubq_s16(int16x8_t a, int16x8_t b) { return __V(SUBS, a, b); }
__SI int16x8_t vnegq_s16(int16x8_t a) { return -a; }
__SI int16x8_t vabsq_s16(int16x8_t a) { return __V(ABS, a, a); }
__SI int16x8_t vmaxq_s16(int16x8_t a, int16x8_t b) { return __V(MAX, a, b); }
__SI int16x8_t vminq_s16(int16x8_t a, int16x8_t b) { return __V(MIN, a, b); }
__SI int16x8_t vrhaddq_s16(int16x8_t a, int16x8_t b) { return __V(AVG, a, b); }
__SI int16x8_t vmlaq_s16(int16x8_t a, int16x8_t b, int16x8_t c) { return __N(MLA, int16x8_t, b, c, a, 0); }
__SI int16x8_t vmlsq_s16(int16x8_t a, int16x8_t b, int16x8_t c) { return __N(MLS, int16x8_t, b, c, a, 0); }
__SI int32x4_t vpaddlq_s16(int16x8_t a) { return __N(PADDL, int32x4_t, a, 0, 0, 0); }
__SI int32x4_t vpadalq_s16(int32x4_t acc, int16x8_t a) { return __N(PADAL, int32x4_t, a, 0, acc, 0); }

__SI int32x4_t vmull_s16(int16x4_t a, int16x4_t b) { return __N(MULL, int32x4_t, a, b, 0, 0); }
__SI int32x4_t vmull_high_s16(int16x8_t a, int16x8_t b) { return __N(MULL2, int32x4_t, a, b, 0, 0); }
__SI int32x4_t vmlal_s16(int32x4_t acc, int16x4_t a, int16x4_t b) { return __N(MLAL, int32x4_t, a, b, acc, 0); }
__SI int32x4_t vmlal_high_s16(int32x4_t acc, int16x8_t a, int16x8_t b) { return __N(MLAL2, int32x4_t, a, b, acc, 0); }
__SI int32x4_t vmovl_s16(int16x4_t a) { return __N(MOVL, int32x4_t, a, 0, 0, 0); }
__SI int32x4_t vmovl_high_s16(int16x8_t a) { return __N(MOVL2, int32x4_t, a, 0, 0, 0); }
__SI int8x8_t vmovn_s16(int16x8_t a) { return __N(XTN, int8x8_t, a, 0, 0, 0); }
__SI int8x8_t vqmovn_s16(int16x8_t a) { return __N(QXTN, int8x8_t, a, 0, 0, 0); }
__SI uint8x8_t vqmovun_s16(int16x8_t a) { return __N(QXTUN, uint8x8_t, a, 0, 0, 0); }
__SI int16x4_t vget_low_s16(int16x8_t a) { int16x4_t r; memcpy(&r, &a, 8); return r; }
__SI int16x4_t vget_high_s16(int16x8_t a) { int16x4_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
__SI int16x8_t vcombine_s16(int16x4_t lo, int16x4_t hi) { int16x8_t r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }

/* uint16x4_t */
__SI uint16x4_t vld1_u16(const unsigned short *p) { uint16x4_t r; memcpy(&r, p, 8); return r; }
__SI void vst1_u16(unsigned short *p, uint16x4_t a) { memcpy(p, &a, 8); }
__SI uint16x4_t vdup_n_u16(unsigned short x) { return __N(SPLAT, uint16x4_t, x, 0, 0, 0); }
__SI uint16x4_t vmov_n_u16(unsigned short x) { return vdup_n_u16(x); }
__SI uint16x4_t vld1_dup_u16(const unsigned short *p) { return vdup_n_u16(*p); }
__SI uint16x4_t vadd_u16(uint16x4_t a, uint16x4_t b) { return a + b; }
__SI uint16x4_t vsub_u16(uint16x4_t a, uint16x4_t b) { return a - b; }
__SI uint16x4_t vmul_u16(uint16x4_t a, uint16x4_t b) { return a * b; }
__SI uint16x4_t vceq_u16(uint16x4_t a, uint16x4_t b) { return (uint16x4_t)(a == b); }
__SI uint16x4_t vcgt_u16(uint16x4_t a, uint16x4_t b) { return (uint16x4_t)(a > b); }
__SI uint16x4_t vcge_u16(uint16x4_t a, uint16x4_t b) { return (uint16x4_t)(a >= b); }
__SI uint16x4_t vclt_u16(uint16x4_t a, uint16x4_t b) { return (uint16x4_t)(a < b); }
__SI uint16x4_t vcle_u16(uint16x4_t a, uint16x4_t b) { return (uint16x4_t)(a <= b); }
__SI uint16x4_t vbsl_u16(uint16x4_t m, uint16x4_t a, uint16x4_t b) { return __N(BSL, uint16x4_t, a, b, (uint16x4_t)m, 0); }
__SI uint16x4_t vzip1_u16(uint16x4_t a, uint16x4_t b) { return __V(UNPCKLO, a, b); }
__SI uint16x4_t vzip2_u16(uint16x4_t a, uint16x4_t b) { return __V(UNPCKHI, a, b); }
__SI uint16x4_t vuzp1_u16(uint16x4_t a, uint16x4_t b) { return __N(UZP1, uint16x4_t, a, b, 0, 0); }
__SI uint16x4_t vuzp2_u16(uint16x4_t a, uint16x4_t b) { return __N(UZP2, uint16x4_t, a, b, 0, 0); }
__SI uint16x4_t vtrn1_u16(uint16x4_t a, uint16x4_t b) { return __N(TRN1, uint16x4_t, a, b, 0, 0); }
__SI uint16x4_t vtrn2_u16(uint16x4_t a, uint16x4_t b) { return __N(TRN2, uint16x4_t, a, b, 0, 0); }
#define vext_u16(a, b, n) __N(EXT, uint16x4_t, (uint16x4_t)(a), (uint16x4_t)(b), 0, (n) * 2)
#define vget_lane_u16(a, n) (((uint16x4_t)(a))[n])
#define vset_lane_u16(x, a, n) ({ uint16x4_t __t = (a); __t[n] = (x); __t; })
#define vdup_lane_u16(a, n) __N(DUPL, uint16x4_t, (uint16x4_t)(a), 0, 0, n)
__SI uint16x4_t vpadd_u16(uint16x4_t a, uint16x4_t b) { return __N(ADDP, uint16x4_t, a, b, 0, 0); }
__SI unsigned short vaddv_u16(uint16x4_t a) { return __N(ADDV, unsigned short, a, 0, 0, 0); }
__SI uint16x4_t vand_u16(uint16x4_t a, uint16x4_t b) { return a & b; }
__SI uint16x4_t vorr_u16(uint16x4_t a, uint16x4_t b) { return a | b; }
__SI uint16x4_t veor_u16(uint16x4_t a, uint16x4_t b) { return a ^ b; }
__SI uint16x4_t vbic_u16(uint16x4_t a, uint16x4_t b) { return __V(ANDNOT, b, a); }
__SI uint16x4_t vmvn_u16(uint16x4_t a) { return ~a; }
#define vshl_n_u16(a, n) ((uint16x4_t)(a) << (n))
#define vshr_n_u16(a, n) ((uint16x4_t)(a) >> (n))
__SI uint16x4_t vshl_u16(uint16x4_t a, int16x4_t b) { return __V(SHL, a, (uint16x4_t)b); }
__SI uint16x4_t vqadd_u16(uint16x4_t a, uint16x4_t b) { return __V(ADDS, a, b); }
__SI uint16x4_t vqsub_u16(uint16x4_t a, uint16x4_t b) { return __V(SUBS, a, b); }
__SI uint16x4_t vmax_u16(uint16x4_t a, uint16x4_t b) { return __V(MAX, a, b); }
__SI uint16x4_t vmin_u16(uint16x4_t a, uint16x4_t b) { return __V(MIN, a, b); }
__SI uint16x4_t vrhadd_u16(uint16x4_t a, uint16x4_t b) { return __V(AVG, a, b); }
__SI uint16x4_t vmla_u16(uint16x4_t a, uint16x4_t b, uint16x4_t c) { return __N(MLA, uint16x4_t, b, c, a, 0); }
__SI uint16x4_t vmls_u16(uint16x4_t a, uint16x4_t b, uint16x4_t c) { return __N(MLS, uint16x4_t, b, c, a, 0); }
__SI uint32x2_t vpaddl_u16(uint16x4_t a) { return __N(PADDL, uint32x2_t, a, 0, 0, 0); }
__SI uint32x2_t vpadal_u16(uint32x2_t acc, uint16x4_t a) { return __N(PADAL, uint32x2_t, a, 0, acc, 0); }

/* uint16x8_t */
__SI uint16x8_t vld1q_u16(const unsigned short *p) { uint16x8_t r; memcpy(&r, p, 16); return r; }
__SI void vst1q_u16(unsigned short *p, uint16x8_t a) { memcpy(p, &a, 16); }
__SI uint16x8_t vdupq_n_u16(unsigned short x) { return __N(SPLAT, uint16x8_t, x, 0, 0, 0); }
__SI uint16x8_t vmovq_n_u16(unsigned short x) { return vdupq_n_u16(x); }
__SI uint16x8_t vld1q_dup_u16(const unsigned short *p) { return vdupq_n_u16(*p); }
__SI uint16x8_t vaddq_u16(uint16x8_t a, uint16x8_t b) { return a + b; }
__SI uint16x8_t vsubq_u16(uint16x8_t a, uint16x8_t b) { return a - b; }
__SI uint16x8_t vmulq_u16(uint16x8_t a, uint16x8_t b) { return a * b; }
__SI uint16x8_t vceqq_u16(uint16x8_t a, uint16x8_t b) { return (uint16x8_t)(a == b); }
__SI uint16x8_t vcgtq_u16(uint16x8_t a, uint16x8_t b) { return (uint16x8_t)(a > b); }
__SI uint16x8_t vcgeq_u16(uint16x8_t a, uint16x8_t b) { return (uint16x8_t)(a >= b); }
__SI uint16x8_t vcltq_u16(uint16x8_t a, uint16x8_t b) { return (uint16x8_t)(a < b); }
__SI uint16x8_t vcleq_u16(uint16x8_t a, uint16x8_t b) { return (uint16x8_t)(a <= b); }
__SI uint16x8_t vbslq_u16(uint16x8_t m, uint16x8_t a, uint16x8_t b) { return __N(BSL, uint16x8_t, a, b, (uint16x8_t)m, 0); }
__SI uint16x8_t vzip1q_u16(uint16x8_t a, uint16x8_t b) { return __V(UNPCKLO, a, b); }
__SI uint16x8_t vzip2q_u16(uint16x8_t a, uint16x8_t b) { return __V(UNPCKHI, a, b); }
__SI uint16x8_t vuzp1q_u16(uint16x8_t a, uint16x8_t b) { return __N(UZP1, uint16x8_t, a, b, 0, 0); }
__SI uint16x8_t vuzp2q_u16(uint16x8_t a, uint16x8_t b) { return __N(UZP2, uint16x8_t, a, b, 0, 0); }
__SI uint16x8_t vtrn1q_u16(uint16x8_t a, uint16x8_t b) { return __N(TRN1, uint16x8_t, a, b, 0, 0); }
__SI uint16x8_t vtrn2q_u16(uint16x8_t a, uint16x8_t b) { return __N(TRN2, uint16x8_t, a, b, 0, 0); }
#define vextq_u16(a, b, n) __N(EXT, uint16x8_t, (uint16x8_t)(a), (uint16x8_t)(b), 0, (n) * 2)
#define vgetq_lane_u16(a, n) (((uint16x8_t)(a))[n])
#define vsetq_lane_u16(x, a, n) ({ uint16x8_t __t = (a); __t[n] = (x); __t; })
#define vdupq_laneq_u16(a, n) __N(DUPL, uint16x8_t, (uint16x8_t)(a), 0, 0, n)
__SI uint16x8_t vpaddq_u16(uint16x8_t a, uint16x8_t b) { return __N(ADDP, uint16x8_t, a, b, 0, 0); }
__SI unsigned short vaddvq_u16(uint16x8_t a) { return __N(ADDV, unsigned short, a, 0, 0, 0); }
__SI uint16x8_t vandq_u16(uint16x8_t a, uint16x8_t b) { return a & b; }
__SI uint16x8_t vorrq_u16(uint16x8_t a, uint16x8_t b) { return a | b; }
__SI uint16x8_t veorq_u16(uint16x8_t a, uint16x8_t b) { return a ^ b; }
__SI uint16x8_t vbicq_u16(uint16x8_t a, uint16x8_t b) { return __V(ANDNOT, b, a); }
__SI uint16x8_t vmvnq_u16(uint16x8_t a) { return ~a; }
#define vshlq_n_u16(a, n) ((uint16x8_t)(a) << (n))
#define vshrq_n_u16(a, n) ((uint16x8_t)(a) >> (n))
__SI uint16x8_t vshlq_u16(uint16x8_t a, int16x8_t b) { return __V(SHL, a, (uint16x8_t)b); }
__SI uint16x8_t vqaddq_u16(uint16x8_t a, uint16x8_t b) { return __V(ADDS, a, b); }
__SI uint16x8_t vqsubq_u16(uint16x8_t a, uint16x8_t b) { return __V(SUBS, a, b); }
__SI uint16x8_t vmaxq_u16(uint16x8_t a, uint16x8_t b) { return __V(MAX, a, b); }
__SI uint16x8_t vminq_u16(uint16x8_t a, uint16x8_t b) { return __V(MIN, a, b); }
__SI uint16x8_t vrhaddq_u16(uint16x8_t a, uint16x8_t b) { return __V(AVG, a, b); }
__SI uint16x8_t vmlaq_u16(uint16x8_t a, uint16x8_t b, uint16x8_t c) { return __N(MLA, uint16x8_t, b, c, a, 0); }
__SI uint16x8_t vmlsq_u16(uint16x8_t a, uint16x8_t b, uint16x8_t c) { return __N(MLS, uint16x8_t, b, c, a, 0); }
__SI uint32x4_t vpaddlq_u16(uint16x8_t a) { return __N(PADDL, uint32x4_t, a, 0, 0, 0); }
__SI uint32x4_t vpadalq_u16(uint32x4_t acc, uint16x8_t a) { return __N(PADAL, uint32x4_t, a, 0, acc, 0); }

__SI uint32x4_t vmull_u16(uint16x4_t a, uint16x4_t b) { return __N(MULL, uint32x4_t, a, b, 0, 0); }
__SI uint32x4_t vmull_high_u16(uint16x8_t a, uint16x8_t b) { return __N(MULL2, uint32x4_t, a, b, 0, 0); }
__SI uint32x4_t vmlal_u16(uint32x4_t acc, uint16x4_t a, uint16x4_t b) { return __N(MLAL, uint32x4_t, a, b, acc, 0); }
__SI uint32x4_t vmlal_high_u16(uint32x4_t acc, uint16x8_t a, uint16x8_t b) { return __N(MLAL2, uint32x4_t, a, b, acc, 0); }
__SI uint32x4_t vmovl_u16(uint16x4_t a) { return __N(MOVL, uint32x4_t, a, 0, 0, 0); }
__SI uint32x4_t vmovl_high_u16(uint16x8_t a) { return __N(MOVL2, uint32x4_t, a, 0, 0, 0); }
__SI uint8x8_t vmovn_u16(uint16x8_t a) { return __N(XTN, uint8x8_t, a, 0, 0, 0); }
__SI uint8x8_t vqmovn_u16(uint16x8_t a) { return __N(QXTN, uint8x8_t, a, 0, 0, 0); }
__SI uint16x4_t vget_low_u16(uint16x8_t a) { uint16x4_t r; memcpy(&r, &a, 8); return r; }
__SI uint16x4_t vget_high_u16(uint16x8_t a) { uint16x4_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
__SI uint16x8_t vcombine_u16(uint16x4_t lo, uint16x4_t hi) { uint16x8_t r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }

/* int32x2_t */
__SI int32x2_t vld1_s32(const int *p) { int32x2_t r; memcpy(&r, p, 8); return r; }
__SI void vst1_s32(int *p, int32x2_t a) { memcpy(p, &a, 8); }
__SI int32x2_t vdup_n_s32(int x) { return __N(SPLAT, int32x2_t, x, 0, 0, 0); }
__SI int32x2_t vmov_n_s32(int x) { return vdup_n_s32(x); }
__SI int32x2_t vld1_dup_s32(const int *p) { return vdup_n_s32(*p); }
__SI int32x2_t vadd_s32(int32x2_t a, int32x2_t b) { return a + b; }
__SI int32x2_t vsub_s32(int32x2_t a, int32x2_t b) { return a - b; }
__SI int32x2_t vmul_s32(int32x2_t a, int32x2_t b) { return a * b; }
__SI uint32x2_t vceq_s32(int32x2_t a, int32x2_t b) { return (uint32x2_t)(a == b); }
__SI uint32x2_t vcgt_s32(int32x2_t a, int32x2_t b) { return (uint32x2_t)(a > b); }
__SI uint32x2_t vcge_s32(int32x2_t a, int32x2_t b) { return (uint32x2_t)(a >= b); }
__SI uint32x2_t vclt_s32(int32x2_t a, int32x2_t b) { return (uint32x2_t)(a < b); }
__SI uint32x2_t vcle_s32(int32x2_t a, int32x2_t b) { return (uint32x2_t)(a <= b); }
__SI int32x2_t vbsl_s32(uint32x2_t m, int32x2_t a, int32x2_t b) { return __N(BSL, int32x2_t, a, b, (int32x2_t)m, 0); }
__SI int32x2_t vzip1_s32(int32x2_t a, int32x2_t b) { return __V(UNPCKLO, a, b); }
__SI int32x2_t vzip2_s32(int32x2_t a, int32x2_t b) { return __V(UNPCKHI, a, b); }
__SI int32x2_t vuzp1_s32(int32x2_t a, int32x2_t b) { return __N(UZP1, int32x2_t, a, b, 0, 0); }
__SI int32x2_t vuzp2_s32(int32x2_t a, int32x2_t b) { return __N(UZP2, int32x2_t, a, b, 0, 0); }
__SI int32x2_t vtrn1_s32(int32x2_t a, int32x2_t b) { return __N(TRN1, int32x2_t, a, b, 0, 0); }
__SI int32x2_t vtrn2_s32(int32x2_t a, int32x2_t b) { return __N(TRN2, int32x2_t, a, b, 0, 0); }
#define vext_s32(a, b, n) __N(EXT, int32x2_t, (int32x2_t)(a), (int32x2_t)(b), 0, (n) * 4)
#define vget_lane_s32(a, n) (((int32x2_t)(a))[n])
#define vset_lane_s32(x, a, n) ({ int32x2_t __t = (a); __t[n] = (x); __t; })
#define vdup_lane_s32(a, n) __N(DUPL, int32x2_t, (int32x2_t)(a), 0, 0, n)
__SI int32x2_t vpadd_s32(int32x2_t a, int32x2_t b) { return __N(ADDP, int32x2_t, a, b, 0, 0); }
__SI int vaddv_s32(int32x2_t a) { return __N(ADDV, int, a, 0, 0, 0); }
__SI int32x2_t vand_s32(int32x2_t a, int32x2_t b) { return a & b; }
__SI int32x2_t vorr_s32(int32x2_t a, int32x2_t b) { return a | b; }
__SI int32x2_t veor_s32(int32x2_t a, int32x2_t b) { return a ^ b; }
__SI int32x2_t vbic_s32(int32x2_t a, int32x2_t b) { return __V(ANDNOT, b, a); }
__SI int32x2_t vmvn_s32(int32x2_t a) { return ~a; }
#define vshl_n_s32(a, n) ((int32x2_t)(a) << (n))
#define vshr_n_s32(a, n) ((int32x2_t)(a) >> (n))
__SI int32x2_t vshl_s32(int32x2_t a, int32x2_t b) { return __V(SHL, a, (int32x2_t)b); }
__SI int32x2_t vqadd_s32(int32x2_t a, int32x2_t b) { return __V(ADDS, a, b); }
__SI int32x2_t vqsub_s32(int32x2_t a, int32x2_t b) { return __V(SUBS, a, b); }
__SI int32x2_t vneg_s32(int32x2_t a) { return -a; }
__SI int32x2_t vabs_s32(int32x2_t a) { return __V(ABS, a, a); }
__SI int32x2_t vmax_s32(int32x2_t a, int32x2_t b) { return __V(MAX, a, b); }
__SI int32x2_t vmin_s32(int32x2_t a, int32x2_t b) { return __V(MIN, a, b); }
__SI int32x2_t vrhadd_s32(int32x2_t a, int32x2_t b) { return __V(AVG, a, b); }
__SI int32x2_t vmla_s32(int32x2_t a, int32x2_t b, int32x2_t c) { return __N(MLA, int32x2_t, b, c, a, 0); }
__SI int32x2_t vmls_s32(int32x2_t a, int32x2_t b, int32x2_t c) { return __N(MLS, int32x2_t, b, c, a, 0); }
__SI int64x1_t vpaddl_s32(int32x2_t a) { return __N(PADDL, int64x1_t, a, 0, 0, 0); }
__SI int64x1_t vpadal_s32(int64x1_t acc, int32x2_t a) { return __N(PADAL, int64x1_t, a, 0, acc, 0); }

/* int32x4_t */
__SI int32x4_t vld1q_s32(const int *p) { int32x4_t r; memcpy(&r, p, 16); return r; }
__SI void vst1q_s32(int *p, int32x4_t a) { memcpy(p, &a, 16); }
__SI int32x4_t vdupq_n_s32(int x) { return __N(SPLAT, int32x4_t, x, 0, 0, 0); }
__SI int32x4_t vmovq_n_s32(int x) { return vdupq_n_s32(x); }
__SI int32x4_t vld1q_dup_s32(const int *p) { return vdupq_n_s32(*p); }
__SI int32x4_t vaddq_s32(int32x4_t a, int32x4_t b) { return a + b; }
__SI int32x4_t vsubq_s32(int32x4_t a, int32x4_t b) { return a - b; }
__SI int32x4_t vmulq_s32(int32x4_t a, int32x4_t b) { return a * b; }
__SI uint32x4_t vceqq_s32(int32x4_t a, int32x4_t b) { return (uint32x4_t)(a == b); }
__SI uint32x4_t vcgtq_s32(int32x4_t a, int32x4_t b) { return (uint32x4_t)(a > b); }
__SI uint32x4_t vcgeq_s32(int32x4_t a, int32x4_t b) { return (uint32x4_t)(a >= b); }
__SI uint32x4_t vcltq_s32(int32x4_t a, int32x4_t b) { return (uint32x4_t)(a < b); }
__SI uint32x4_t vcleq_s32(int32x4_t a, int32x4_t b) { return (uint32x4_t)(a <= b); }
__SI int32x4_t vbslq_s32(uint32x4_t m, int32x4_t a, int32x4_t b) { return __N(BSL, int32x4_t, a, b, (int32x4_t)m, 0); }
__SI int32x4_t vzip1q_s32(int32x4_t a, int32x4_t b) { return __V(UNPCKLO, a, b); }
__SI int32x4_t vzip2q_s32(int32x4_t a, int32x4_t b) { return __V(UNPCKHI, a, b); }
__SI int32x4_t vuzp1q_s32(int32x4_t a, int32x4_t b) { return __N(UZP1, int32x4_t, a, b, 0, 0); }
__SI int32x4_t vuzp2q_s32(int32x4_t a, int32x4_t b) { return __N(UZP2, int32x4_t, a, b, 0, 0); }
__SI int32x4_t vtrn1q_s32(int32x4_t a, int32x4_t b) { return __N(TRN1, int32x4_t, a, b, 0, 0); }
__SI int32x4_t vtrn2q_s32(int32x4_t a, int32x4_t b) { return __N(TRN2, int32x4_t, a, b, 0, 0); }
#define vextq_s32(a, b, n) __N(EXT, int32x4_t, (int32x4_t)(a), (int32x4_t)(b), 0, (n) * 4)
#define vgetq_lane_s32(a, n) (((int32x4_t)(a))[n])
#define vsetq_lane_s32(x, a, n) ({ int32x4_t __t = (a); __t[n] = (x); __t; })
#define vdupq_laneq_s32(a, n) __N(DUPL, int32x4_t, (int32x4_t)(a), 0, 0, n)
__SI int32x4_t vpaddq_s32(int32x4_t a, int32x4_t b) { return __N(ADDP, int32x4_t, a, b, 0, 0); }
__SI int vaddvq_s32(int32x4_t a) { return __N(ADDV, int, a, 0, 0, 0); }
__SI int32x4_t vandq_s32(int32x4_t a, int32x4_t b) { return a & b; }
__SI int32x4_t vorrq_s32(int32x4_t a, int32x4_t b) { return a | b; }
__SI int32x4_t veorq_s32(int32x4_t a, int32x4_t b) { return a ^ b; }
__SI int32x4_t vbicq_s32(int32x4_t a, int32x4_t b) { return __V(ANDNOT, b, a); }
__SI int32x4_t vmvnq_s32(int32x4_t a) { return ~a; }
#define vshlq_n_s32(a, n) ((int32x4_t)(a) << (n))
#define vshrq_n_s32(a, n) ((int32x4_t)(a) >> (n))
__SI int32x4_t vshlq_s32(int32x4_t a, int32x4_t b) { return __V(SHL, a, (int32x4_t)b); }
__SI int32x4_t vqaddq_s32(int32x4_t a, int32x4_t b) { return __V(ADDS, a, b); }
__SI int32x4_t vqsubq_s32(int32x4_t a, int32x4_t b) { return __V(SUBS, a, b); }
__SI int32x4_t vnegq_s32(int32x4_t a) { return -a; }
__SI int32x4_t vabsq_s32(int32x4_t a) { return __V(ABS, a, a); }
__SI int32x4_t vmaxq_s32(int32x4_t a, int32x4_t b) { return __V(MAX, a, b); }
__SI int32x4_t vminq_s32(int32x4_t a, int32x4_t b) { return __V(MIN, a, b); }
__SI int32x4_t vrhaddq_s32(int32x4_t a, int32x4_t b) { return __V(AVG, a, b); }
__SI int32x4_t vmlaq_s32(int32x4_t a, int32x4_t b, int32x4_t c) { return __N(MLA, int32x4_t, b, c, a, 0); }
__SI int32x4_t vmlsq_s32(int32x4_t a, int32x4_t b, int32x4_t c) { return __N(MLS, int32x4_t, b, c, a, 0); }
__SI int64x2_t vpaddlq_s32(int32x4_t a) { return __N(PADDL, int64x2_t, a, 0, 0, 0); }
__SI int64x2_t vpadalq_s32(int64x2_t acc, int32x4_t a) { return __N(PADAL, int64x2_t, a, 0, acc, 0); }

__SI int64x2_t vmull_s32(int32x2_t a, int32x2_t b) { return __N(MULL, int64x2_t, a, b, 0, 0); }
__SI int64x2_t vmull_high_s32(int32x4_t a, int32x4_t b) { return __N(MULL2, int64x2_t, a, b, 0, 0); }
__SI int64x2_t vmlal_s32(int64x2_t acc, int32x2_t a, int32x2_t b) { return __N(MLAL, int64x2_t, a, b, acc, 0); }
__SI int64x2_t vmlal_high_s32(int64x2_t acc, int32x4_t a, int32x4_t b) { return __N(MLAL2, int64x2_t, a, b, acc, 0); }
__SI int64x2_t vmovl_s32(int32x2_t a) { return __N(MOVL, int64x2_t, a, 0, 0, 0); }
__SI int64x2_t vmovl_high_s32(int32x4_t a) { return __N(MOVL2, int64x2_t, a, 0, 0, 0); }
__SI int16x4_t vmovn_s32(int32x4_t a) { return __N(XTN, int16x4_t, a, 0, 0, 0); }
__SI int16x4_t vqmovn_s32(int32x4_t a) { return __N(QXTN, int16x4_t, a, 0, 0, 0); }
__SI uint16x4_t vqmovun_s32(int32x4_t a) { return __N(QXTUN, uint16x4_t, a, 0, 0, 0); }
__SI int32x2_t vget_low_s32(int32x4_t a) { int32x2_t r; memcpy(&r, &a, 8); return r; }
__SI int32x2_t vget_high_s32(int32x4_t a) { int32x2_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
__SI int32x4_t vcombine_s32(int32x2_t lo, int32x2_t hi) { int32x4_t r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }

/* uint32x2_t */
__SI uint32x2_t vld1_u32(const unsigned *p) { uint32x2_t r; memcpy(&r, p, 8); return r; }
__SI void vst1_u32(unsigned *p, uint32x2_t a) { memcpy(p, &a, 8); }
__SI uint32x2_t vdup_n_u32(unsigned x) { return __N(SPLAT, uint32x2_t, x, 0, 0, 0); }
__SI uint32x2_t vmov_n_u32(unsigned x) { return vdup_n_u32(x); }
__SI uint32x2_t vld1_dup_u32(const unsigned *p) { return vdup_n_u32(*p); }
__SI uint32x2_t vadd_u32(uint32x2_t a, uint32x2_t b) { return a + b; }
__SI uint32x2_t vsub_u32(uint32x2_t a, uint32x2_t b) { return a - b; }
__SI uint32x2_t vmul_u32(uint32x2_t a, uint32x2_t b) { return a * b; }
__SI uint32x2_t vceq_u32(uint32x2_t a, uint32x2_t b) { return (uint32x2_t)(a == b); }
__SI uint32x2_t vcgt_u32(uint32x2_t a, uint32x2_t b) { return (uint32x2_t)(a > b); }
__SI uint32x2_t vcge_u32(uint32x2_t a, uint32x2_t b) { return (uint32x2_t)(a >= b); }
__SI uint32x2_t vclt_u32(uint32x2_t a, uint32x2_t b) { return (uint32x2_t)(a < b); }
__SI uint32x2_t vcle_u32(uint32x2_t a, uint32x2_t b) { return (uint32x2_t)(a <= b); }
__SI uint32x2_t vbsl_u32(uint32x2_t m, uint32x2_t a, uint32x2_t b) { return __N(BSL, uint32x2_t, a, b, (uint32x2_t)m, 0); }
__SI uint32x2_t vzip1_u32(uint32x2_t a, uint32x2_t b) { return __V(UNPCKLO, a, b); }
__SI uint32x2_t vzip2_u32(uint32x2_t a, uint32x2_t b) { return __V(UNPCKHI, a, b); }
__SI uint32x2_t vuzp1_u32(uint32x2_t a, uint32x2_t b) { return __N(UZP1, uint32x2_t, a, b, 0, 0); }
__SI uint32x2_t vuzp2_u32(uint32x2_t a, uint32x2_t b) { return __N(UZP2, uint32x2_t, a, b, 0, 0); }
__SI uint32x2_t vtrn1_u32(uint32x2_t a, uint32x2_t b) { return __N(TRN1, uint32x2_t, a, b, 0, 0); }
__SI uint32x2_t vtrn2_u32(uint32x2_t a, uint32x2_t b) { return __N(TRN2, uint32x2_t, a, b, 0, 0); }
#define vext_u32(a, b, n) __N(EXT, uint32x2_t, (uint32x2_t)(a), (uint32x2_t)(b), 0, (n) * 4)
#define vget_lane_u32(a, n) (((uint32x2_t)(a))[n])
#define vset_lane_u32(x, a, n) ({ uint32x2_t __t = (a); __t[n] = (x); __t; })
#define vdup_lane_u32(a, n) __N(DUPL, uint32x2_t, (uint32x2_t)(a), 0, 0, n)
__SI uint32x2_t vpadd_u32(uint32x2_t a, uint32x2_t b) { return __N(ADDP, uint32x2_t, a, b, 0, 0); }
__SI unsigned vaddv_u32(uint32x2_t a) { return __N(ADDV, unsigned, a, 0, 0, 0); }
__SI uint32x2_t vand_u32(uint32x2_t a, uint32x2_t b) { return a & b; }
__SI uint32x2_t vorr_u32(uint32x2_t a, uint32x2_t b) { return a | b; }
__SI uint32x2_t veor_u32(uint32x2_t a, uint32x2_t b) { return a ^ b; }
__SI uint32x2_t vbic_u32(uint32x2_t a, uint32x2_t b) { return __V(ANDNOT, b, a); }
__SI uint32x2_t vmvn_u32(uint32x2_t a) { return ~a; }
#define vshl_n_u32(a, n) ((uint32x2_t)(a) << (n))
#define vshr_n_u32(a, n) ((uint32x2_t)(a) >> (n))
__SI uint32x2_t vshl_u32(uint32x2_t a, int32x2_t b) { return __V(SHL, a, (uint32x2_t)b); }
__SI uint32x2_t vqadd_u32(uint32x2_t a, uint32x2_t b) { return __V(ADDS, a, b); }
__SI uint32x2_t vqsub_u32(uint32x2_t a, uint32x2_t b) { return __V(SUBS, a, b); }
__SI uint32x2_t vmax_u32(uint32x2_t a, uint32x2_t b) { return __V(MAX, a, b); }
__SI uint32x2_t vmin_u32(uint32x2_t a, uint32x2_t b) { return __V(MIN, a, b); }
__SI uint32x2_t vrhadd_u32(uint32x2_t a, uint32x2_t b) { return __V(AVG, a, b); }
__SI uint32x2_t vmla_u32(uint32x2_t a, uint32x2_t b, uint32x2_t c) { return __N(MLA, uint32x2_t, b, c, a, 0); }
__SI uint32x2_t vmls_u32(uint32x2_t a, uint32x2_t b, uint32x2_t c) { return __N(MLS, uint32x2_t, b, c, a, 0); }
__SI uint64x1_t vpaddl_u32(uint32x2_t a) { return __N(PADDL, uint64x1_t, a, 0, 0, 0); }
__SI uint64x1_t vpadal_u32(uint64x1_t acc, uint32x2_t a) { return __N(PADAL, uint64x1_t, a, 0, acc, 0); }

/* uint32x4_t */
__SI uint32x4_t vld1q_u32(const unsigned *p) { uint32x4_t r; memcpy(&r, p, 16); return r; }
__SI void vst1q_u32(unsigned *p, uint32x4_t a) { memcpy(p, &a, 16); }
__SI uint32x4_t vdupq_n_u32(unsigned x) { return __N(SPLAT, uint32x4_t, x, 0, 0, 0); }
__SI uint32x4_t vmovq_n_u32(unsigned x) { return vdupq_n_u32(x); }
__SI uint32x4_t vld1q_dup_u32(const unsigned *p) { return vdupq_n_u32(*p); }
__SI uint32x4_t vaddq_u32(uint32x4_t a, uint32x4_t b) { return a + b; }
__SI uint32x4_t vsubq_u32(uint32x4_t a, uint32x4_t b) { return a - b; }
__SI uint32x4_t vmulq_u32(uint32x4_t a, uint32x4_t b) { return a * b; }
__SI uint32x4_t vceqq_u32(uint32x4_t a, uint32x4_t b) { return (uint32x4_t)(a == b); }
__SI uint32x4_t vcgtq_u32(uint32x4_t a, uint32x4_t b) { return (uint32x4_t)(a > b); }
__SI uint32x4_t vcgeq_u32(uint32x4_t a, uint32x4_t b) { return (uint32x4_t)(a >= b); }
__SI uint32x4_t vcltq_u32(uint32x4_t a, uint32x4_t b) { return (uint32x4_t)(a < b); }
__SI uint32x4_t vcleq_u32(uint32x4_t a, uint32x4_t b) { return (uint32x4_t)(a <= b); }
__SI uint32x4_t vbslq_u32(uint32x4_t m, uint32x4_t a, uint32x4_t b) { return __N(BSL, uint32x4_t, a, b, (uint32x4_t)m, 0); }
__SI uint32x4_t vzip1q_u32(uint32x4_t a, uint32x4_t b) { return __V(UNPCKLO, a, b); }
__SI uint32x4_t vzip2q_u32(uint32x4_t a, uint32x4_t b) { return __V(UNPCKHI, a, b); }
__SI uint32x4_t vuzp1q_u32(uint32x4_t a, uint32x4_t b) { return __N(UZP1, uint32x4_t, a, b, 0, 0); }
__SI uint32x4_t vuzp2q_u32(uint32x4_t a, uint32x4_t b) { return __N(UZP2, uint32x4_t, a, b, 0, 0); }
__SI uint32x4_t vtrn1q_u32(uint32x4_t a, uint32x4_t b) { return __N(TRN1, uint32x4_t, a, b, 0, 0); }
__SI uint32x4_t vtrn2q_u32(uint32x4_t a, uint32x4_t b) { return __N(TRN2, uint32x4_t, a, b, 0, 0); }
#define vextq_u32(a, b, n) __N(EXT, uint32x4_t, (uint32x4_t)(a), (uint32x4_t)(b), 0, (n) * 4)
#define vgetq_lane_u32(a, n) (((uint32x4_t)(a))[n])
#define vsetq_lane_u32(x, a, n) ({ uint32x4_t __t = (a); __t[n] = (x); __t; })
#define vdupq_laneq_u32(a, n) __N(DUPL, uint32x4_t, (uint32x4_t)(a), 0, 0, n)
__SI uint32x4_t vpaddq_u32(uint32x4_t a, uint32x4_t b) { return __N(ADDP, uint32x4_t, a, b, 0, 0); }
__SI unsigned vaddvq_u32(uint32x4_t a) { return __N(ADDV, unsigned, a, 0, 0, 0); }
__SI uint32x4_t vandq_u32(uint32x4_t a, uint32x4_t b) { return a & b; }
__SI uint32x4_t vorrq_u32(uint32x4_t a, uint32x4_t b) { return a | b; }
__SI uint32x4_t veorq_u32(uint32x4_t a, uint32x4_t b) { return a ^ b; }
__SI uint32x4_t vbicq_u32(uint32x4_t a, uint32x4_t b) { return __V(ANDNOT, b, a); }
__SI uint32x4_t vmvnq_u32(uint32x4_t a) { return ~a; }
#define vshlq_n_u32(a, n) ((uint32x4_t)(a) << (n))
#define vshrq_n_u32(a, n) ((uint32x4_t)(a) >> (n))
__SI uint32x4_t vshlq_u32(uint32x4_t a, int32x4_t b) { return __V(SHL, a, (uint32x4_t)b); }
__SI uint32x4_t vqaddq_u32(uint32x4_t a, uint32x4_t b) { return __V(ADDS, a, b); }
__SI uint32x4_t vqsubq_u32(uint32x4_t a, uint32x4_t b) { return __V(SUBS, a, b); }
__SI uint32x4_t vmaxq_u32(uint32x4_t a, uint32x4_t b) { return __V(MAX, a, b); }
__SI uint32x4_t vminq_u32(uint32x4_t a, uint32x4_t b) { return __V(MIN, a, b); }
__SI uint32x4_t vrhaddq_u32(uint32x4_t a, uint32x4_t b) { return __V(AVG, a, b); }
__SI uint32x4_t vmlaq_u32(uint32x4_t a, uint32x4_t b, uint32x4_t c) { return __N(MLA, uint32x4_t, b, c, a, 0); }
__SI uint32x4_t vmlsq_u32(uint32x4_t a, uint32x4_t b, uint32x4_t c) { return __N(MLS, uint32x4_t, b, c, a, 0); }
__SI uint64x2_t vpaddlq_u32(uint32x4_t a) { return __N(PADDL, uint64x2_t, a, 0, 0, 0); }
__SI uint64x2_t vpadalq_u32(uint64x2_t acc, uint32x4_t a) { return __N(PADAL, uint64x2_t, a, 0, acc, 0); }

__SI uint64x2_t vmull_u32(uint32x2_t a, uint32x2_t b) { return __N(MULL, uint64x2_t, a, b, 0, 0); }
__SI uint64x2_t vmull_high_u32(uint32x4_t a, uint32x4_t b) { return __N(MULL2, uint64x2_t, a, b, 0, 0); }
__SI uint64x2_t vmlal_u32(uint64x2_t acc, uint32x2_t a, uint32x2_t b) { return __N(MLAL, uint64x2_t, a, b, acc, 0); }
__SI uint64x2_t vmlal_high_u32(uint64x2_t acc, uint32x4_t a, uint32x4_t b) { return __N(MLAL2, uint64x2_t, a, b, acc, 0); }
__SI uint64x2_t vmovl_u32(uint32x2_t a) { return __N(MOVL, uint64x2_t, a, 0, 0, 0); }
__SI uint64x2_t vmovl_high_u32(uint32x4_t a) { return __N(MOVL2, uint64x2_t, a, 0, 0, 0); }
__SI uint16x4_t vmovn_u32(uint32x4_t a) { return __N(XTN, uint16x4_t, a, 0, 0, 0); }
__SI uint16x4_t vqmovn_u32(uint32x4_t a) { return __N(QXTN, uint16x4_t, a, 0, 0, 0); }
__SI uint32x2_t vget_low_u32(uint32x4_t a) { uint32x2_t r; memcpy(&r, &a, 8); return r; }
__SI uint32x2_t vget_high_u32(uint32x4_t a) { uint32x2_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
__SI uint32x4_t vcombine_u32(uint32x2_t lo, uint32x2_t hi) { uint32x4_t r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }

/* int64x1_t */
__SI int64x1_t vld1_s64(const long *p) { int64x1_t r; memcpy(&r, p, 8); return r; }
__SI void vst1_s64(long *p, int64x1_t a) { memcpy(p, &a, 8); }
__SI int64x1_t vdup_n_s64(long x) { return __N(SPLAT, int64x1_t, x, 0, 0, 0); }
__SI int64x1_t vmov_n_s64(long x) { return vdup_n_s64(x); }
__SI int64x1_t vld1_dup_s64(const long *p) { return vdup_n_s64(*p); }
__SI int64x1_t vadd_s64(int64x1_t a, int64x1_t b) { return a + b; }
__SI int64x1_t vsub_s64(int64x1_t a, int64x1_t b) { return a - b; }
__SI int64x1_t vmul_s64(int64x1_t a, int64x1_t b) { return a * b; }
__SI uint64x1_t vceq_s64(int64x1_t a, int64x1_t b) { return (uint64x1_t)(a == b); }
__SI uint64x1_t vcgt_s64(int64x1_t a, int64x1_t b) { return (uint64x1_t)(a > b); }
__SI uint64x1_t vcge_s64(int64x1_t a, int64x1_t b) { return (uint64x1_t)(a >= b); }
__SI uint64x1_t vclt_s64(int64x1_t a, int64x1_t b) { return (uint64x1_t)(a < b); }
__SI uint64x1_t vcle_s64(int64x1_t a, int64x1_t b) { return (uint64x1_t)(a <= b); }
__SI int64x1_t vbsl_s64(uint64x1_t m, int64x1_t a, int64x1_t b) { return __N(BSL, int64x1_t, a, b, (int64x1_t)m, 0); }
__SI int64x1_t vzip1_s64(int64x1_t a, int64x1_t b) { return __V(UNPCKLO, a, b); }
__SI int64x1_t vzip2_s64(int64x1_t a, int64x1_t b) { return __V(UNPCKHI, a, b); }
__SI int64x1_t vuzp1_s64(int64x1_t a, int64x1_t b) { return __N(UZP1, int64x1_t, a, b, 0, 0); }
__SI int64x1_t vuzp2_s64(int64x1_t a, int64x1_t b) { return __N(UZP2, int64x1_t, a, b, 0, 0); }
__SI int64x1_t vtrn1_s64(int64x1_t a, int64x1_t b) { return __N(TRN1, int64x1_t, a, b, 0, 0); }
__SI int64x1_t vtrn2_s64(int64x1_t a, int64x1_t b) { return __N(TRN2, int64x1_t, a, b, 0, 0); }
#define vext_s64(a, b, n) __N(EXT, int64x1_t, (int64x1_t)(a), (int64x1_t)(b), 0, (n) * 8)
#define vget_lane_s64(a, n) (((int64x1_t)(a))[n])
#define vset_lane_s64(x, a, n) ({ int64x1_t __t = (a); __t[n] = (x); __t; })
#define vdup_lane_s64(a, n) __N(DUPL, int64x1_t, (int64x1_t)(a), 0, 0, n)
__SI int64x1_t vpadd_s64(int64x1_t a, int64x1_t b) { return __N(ADDP, int64x1_t, a, b, 0, 0); }
__SI int64x1_t vand_s64(int64x1_t a, int64x1_t b) { return a & b; }
__SI int64x1_t vorr_s64(int64x1_t a, int64x1_t b) { return a | b; }
__SI int64x1_t veor_s64(int64x1_t a, int64x1_t b) { return a ^ b; }
__SI int64x1_t vbic_s64(int64x1_t a, int64x1_t b) { return __V(ANDNOT, b, a); }
__SI int64x1_t vmvn_s64(int64x1_t a) { return ~a; }
#define vshl_n_s64(a, n) ((int64x1_t)(a) << (n))
#define vshr_n_s64(a, n) ((int64x1_t)(a) >> (n))
__SI int64x1_t vshl_s64(int64x1_t a, int64x1_t b) { return __V(SHL, a, (int64x1_t)b); }
__SI int64x1_t vqadd_s64(int64x1_t a, int64x1_t b) { return __V(ADDS, a, b); }
__SI int64x1_t vqsub_s64(int64x1_t a, int64x1_t b) { return __V(SUBS, a, b); }
__SI int64x1_t vneg_s64(int64x1_t a) { return -a; }
__SI int64x1_t vabs_s64(int64x1_t a) { return __V(ABS, a, a); }

/* int64x2_t */
__SI int64x2_t vld1q_s64(const long *p) { int64x2_t r; memcpy(&r, p, 16); return r; }
__SI void vst1q_s64(long *p, int64x2_t a) { memcpy(p, &a, 16); }
__SI int64x2_t vdupq_n_s64(long x) { return __N(SPLAT, int64x2_t, x, 0, 0, 0); }
__SI int64x2_t vmovq_n_s64(long x) { return vdupq_n_s64(x); }
__SI int64x2_t vld1q_dup_s64(const long *p) { return vdupq_n_s64(*p); }
__SI int64x2_t vaddq_s64(int64x2_t a, int64x2_t b) { return a + b; }
__SI int64x2_t vsubq_s64(int64x2_t a, int64x2_t b) { return a - b; }
__SI int64x2_t vmulq_s64(int64x2_t a, int64x2_t b) { return a * b; }
__SI uint64x2_t vceqq_s64(int64x2_t a, int64x2_t b) { return (uint64x2_t)(a == b); }
__SI uint64x2_t vcgtq_s64(int64x2_t a, int64x2_t b) { return (uint64x2_t)(a > b); }
__SI uint64x2_t vcgeq_s64(int64x2_t a, int64x2_t b) { return (uint64x2_t)(a >= b); }
__SI uint64x2_t vcltq_s64(int64x2_t a, int64x2_t b) { return (uint64x2_t)(a < b); }
__SI uint64x2_t vcleq_s64(int64x2_t a, int64x2_t b) { return (uint64x2_t)(a <= b); }
__SI int64x2_t vbslq_s64(uint64x2_t m, int64x2_t a, int64x2_t b) { return __N(BSL, int64x2_t, a, b, (int64x2_t)m, 0); }
__SI int64x2_t vzip1q_s64(int64x2_t a, int64x2_t b) { return __V(UNPCKLO, a, b); }
__SI int64x2_t vzip2q_s64(int64x2_t a, int64x2_t b) { return __V(UNPCKHI, a, b); }
__SI int64x2_t vuzp1q_s64(int64x2_t a, int64x2_t b) { return __N(UZP1, int64x2_t, a, b, 0, 0); }
__SI int64x2_t vuzp2q_s64(int64x2_t a, int64x2_t b) { return __N(UZP2, int64x2_t, a, b, 0, 0); }
__SI int64x2_t vtrn1q_s64(int64x2_t a, int64x2_t b) { return __N(TRN1, int64x2_t, a, b, 0, 0); }
__SI int64x2_t vtrn2q_s64(int64x2_t a, int64x2_t b) { return __N(TRN2, int64x2_t, a, b, 0, 0); }
#define vextq_s64(a, b, n) __N(EXT, int64x2_t, (int64x2_t)(a), (int64x2_t)(b), 0, (n) * 8)
#define vgetq_lane_s64(a, n) (((int64x2_t)(a))[n])
#define vsetq_lane_s64(x, a, n) ({ int64x2_t __t = (a); __t[n] = (x); __t; })
#define vdupq_laneq_s64(a, n) __N(DUPL, int64x2_t, (int64x2_t)(a), 0, 0, n)
__SI int64x2_t vpaddq_s64(int64x2_t a, int64x2_t b) { return __N(ADDP, int64x2_t, a, b, 0, 0); }
__SI long vaddvq_s64(int64x2_t a) { return __N(ADDV, long, a, 0, 0, 0); }
__SI int64x2_t vandq_s64(int64x2_t a, int64x2_t b) { return a & b; }
__SI int64x2_t vorrq_s64(int64x2_t a, int64x2_t b) { return a | b; }
__SI int64x2_t veorq_s64(int64x2_t a, int64x2_t b) { return a ^ b; }
__SI int64x2_t vbicq_s64(int64x2_t a, int64x2_t b) { return __V(ANDNOT, b, a); }
__SI int64x2_t vmvnq_s64(int64x2_t a) { return ~a; }
#define vshlq_n_s64(a, n) ((int64x2_t)(a) << (n))
#define vshrq_n_s64(a, n) ((int64x2_t)(a) >> (n))
__SI int64x2_t vshlq_s64(int64x2_t a, int64x2_t b) { return __V(SHL, a, (int64x2_t)b); }
__SI int64x2_t vqaddq_s64(int64x2_t a, int64x2_t b) { return __V(ADDS, a, b); }
__SI int64x2_t vqsubq_s64(int64x2_t a, int64x2_t b) { return __V(SUBS, a, b); }
__SI int64x2_t vnegq_s64(int64x2_t a) { return -a; }
__SI int64x2_t vabsq_s64(int64x2_t a) { return __V(ABS, a, a); }

__SI int32x2_t vmovn_s64(int64x2_t a) { return __N(XTN, int32x2_t, a, 0, 0, 0); }
__SI int32x2_t vqmovn_s64(int64x2_t a) { return __N(QXTN, int32x2_t, a, 0, 0, 0); }
__SI uint32x2_t vqmovun_s64(int64x2_t a) { return __N(QXTUN, uint32x2_t, a, 0, 0, 0); }
__SI int64x1_t vget_low_s64(int64x2_t a) { int64x1_t r; memcpy(&r, &a, 8); return r; }
__SI int64x1_t vget_high_s64(int64x2_t a) { int64x1_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
__SI int64x2_t vcombine_s64(int64x1_t lo, int64x1_t hi) { int64x2_t r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }

/* uint64x1_t */
__SI uint64x1_t vld1_u64(const unsigned long *p) { uint64x1_t r; memcpy(&r, p, 8); return r; }
__SI void vst1_u64(unsigned long *p, uint64x1_t a) { memcpy(p, &a, 8); }
__SI uint64x1_t vdup_n_u64(unsigned long x) { return __N(SPLAT, uint64x1_t, x, 0, 0, 0); }
__SI uint64x1_t vmov_n_u64(unsigned long x) { return vdup_n_u64(x); }
__SI uint64x1_t vld1_dup_u64(const unsigned long *p) { return vdup_n_u64(*p); }
__SI uint64x1_t vadd_u64(uint64x1_t a, uint64x1_t b) { return a + b; }
__SI uint64x1_t vsub_u64(uint64x1_t a, uint64x1_t b) { return a - b; }
__SI uint64x1_t vmul_u64(uint64x1_t a, uint64x1_t b) { return a * b; }
__SI uint64x1_t vceq_u64(uint64x1_t a, uint64x1_t b) { return (uint64x1_t)(a == b); }
__SI uint64x1_t vcgt_u64(uint64x1_t a, uint64x1_t b) { return (uint64x1_t)(a > b); }
__SI uint64x1_t vcge_u64(uint64x1_t a, uint64x1_t b) { return (uint64x1_t)(a >= b); }
__SI uint64x1_t vclt_u64(uint64x1_t a, uint64x1_t b) { return (uint64x1_t)(a < b); }
__SI uint64x1_t vcle_u64(uint64x1_t a, uint64x1_t b) { return (uint64x1_t)(a <= b); }
__SI uint64x1_t vbsl_u64(uint64x1_t m, uint64x1_t a, uint64x1_t b) { return __N(BSL, uint64x1_t, a, b, (uint64x1_t)m, 0); }
__SI uint64x1_t vzip1_u64(uint64x1_t a, uint64x1_t b) { return __V(UNPCKLO, a, b); }
__SI uint64x1_t vzip2_u64(uint64x1_t a, uint64x1_t b) { return __V(UNPCKHI, a, b); }
__SI uint64x1_t vuzp1_u64(uint64x1_t a, uint64x1_t b) { return __N(UZP1, uint64x1_t, a, b, 0, 0); }
__SI uint64x1_t vuzp2_u64(uint64x1_t a, uint64x1_t b) { return __N(UZP2, uint64x1_t, a, b, 0, 0); }
__SI uint64x1_t vtrn1_u64(uint64x1_t a, uint64x1_t b) { return __N(TRN1, uint64x1_t, a, b, 0, 0); }
__SI uint64x1_t vtrn2_u64(uint64x1_t a, uint64x1_t b) { return __N(TRN2, uint64x1_t, a, b, 0, 0); }
#define vext_u64(a, b, n) __N(EXT, uint64x1_t, (uint64x1_t)(a), (uint64x1_t)(b), 0, (n) * 8)
#define vget_lane_u64(a, n) (((uint64x1_t)(a))[n])
#define vset_lane_u64(x, a, n) ({ uint64x1_t __t = (a); __t[n] = (x); __t; })
#define vdup_lane_u64(a, n) __N(DUPL, uint64x1_t, (uint64x1_t)(a), 0, 0, n)
__SI uint64x1_t vpadd_u64(uint64x1_t a, uint64x1_t b) { return __N(ADDP, uint64x1_t, a, b, 0, 0); }
__SI uint64x1_t vand_u64(uint64x1_t a, uint64x1_t b) { return a & b; }
__SI uint64x1_t vorr_u64(uint64x1_t a, uint64x1_t b) { return a | b; }
__SI uint64x1_t veor_u64(uint64x1_t a, uint64x1_t b) { return a ^ b; }
__SI uint64x1_t vbic_u64(uint64x1_t a, uint64x1_t b) { return __V(ANDNOT, b, a); }
__SI uint64x1_t vmvn_u64(uint64x1_t a) { return ~a; }
#define vshl_n_u64(a, n) ((uint64x1_t)(a) << (n))
#define vshr_n_u64(a, n) ((uint64x1_t)(a) >> (n))
__SI uint64x1_t vshl_u64(uint64x1_t a, int64x1_t b) { return __V(SHL, a, (uint64x1_t)b); }
__SI uint64x1_t vqadd_u64(uint64x1_t a, uint64x1_t b) { return __V(ADDS, a, b); }
__SI uint64x1_t vqsub_u64(uint64x1_t a, uint64x1_t b) { return __V(SUBS, a, b); }

/* uint64x2_t */
__SI uint64x2_t vld1q_u64(const unsigned long *p) { uint64x2_t r; memcpy(&r, p, 16); return r; }
__SI void vst1q_u64(unsigned long *p, uint64x2_t a) { memcpy(p, &a, 16); }
__SI uint64x2_t vdupq_n_u64(unsigned long x) { return __N(SPLAT, uint64x2_t, x, 0, 0, 0); }
__SI uint64x2_t vmovq_n_u64(unsigned long x) { return vdupq_n_u64(x); }
__SI uint64x2_t vld1q_dup_u64(const unsigned long *p) { return vdupq_n_u64(*p); }
__SI uint64x2_t vaddq_u64(uint64x2_t a, uint64x2_t b) { return a + b; }
__SI uint64x2_t vsubq_u64(uint64x2_t a, uint64x2_t b) { return a - b; }
__SI uint64x2_t vmulq_u64(uint64x2_t a, uint64x2_t b) { return a * b; }
__SI uint64x2_t vceqq_u64(uint64x2_t a, uint64x2_t b) { return (uint64x2_t)(a == b); }
__SI uint64x2_t vcgtq_u64(uint64x2_t a, uint64x2_t b) { return (uint64x2_t)(a > b); }
__SI uint64x2_t vcgeq_u64(uint64x2_t a, uint64x2_t b) { return (uint64x2_t)(a >= b); }
__SI uint64x2_t vcltq_u64(uint64x2_t a, uint64x2_t b) { return (uint64x2_t)(a < b); }
__SI uint64x2_t vcleq_u64(uint64x2_t a, uint64x2_t b) { return (uint64x2_t)(a <= b); }
__SI uint64x2_t vbslq_u64(uint64x2_t m, uint64x2_t a, uint64x2_t b) { return __N(BSL, uint64x2_t, a, b, (uint64x2_t)m, 0); }
__SI uint64x2_t vzip1q_u64(uint64x2_t a, uint64x2_t b) { return __V(UNPCKLO, a, b); }
__SI uint64x2_t vzip2q_u64(uint64x2_t a, uint64x2_t b) { return __V(UNPCKHI, a, b); }
__SI uint64x2_t vuzp1q_u64(uint64x2_t a, uint64x2_t b) { return __N(UZP1, uint64x2_t, a, b, 0, 0); }
__SI uint64x2_t vuzp2q_u64(uint64x2_t a, uint64x2_t b) { return __N(UZP2, uint64x2_t, a, b, 0, 0); }
__SI uint64x2_t vtrn1q_u64(uint64x2_t a, uint64x2_t b) { return __N(TRN1, uint64x2_t, a, b, 0, 0); }
__SI uint64x2_t vtrn2q_u64(uint64x2_t a, uint64x2_t b) { return __N(TRN2, uint64x2_t, a, b, 0, 0); }
#define vextq_u64(a, b, n) __N(EXT, uint64x2_t, (uint64x2_t)(a), (uint64x2_t)(b), 0, (n) * 8)
#define vgetq_lane_u64(a, n) (((uint64x2_t)(a))[n])
#define vsetq_lane_u64(x, a, n) ({ uint64x2_t __t = (a); __t[n] = (x); __t; })
#define vdupq_laneq_u64(a, n) __N(DUPL, uint64x2_t, (uint64x2_t)(a), 0, 0, n)
__SI uint64x2_t vpaddq_u64(uint64x2_t a, uint64x2_t b) { return __N(ADDP, uint64x2_t, a, b, 0, 0); }
__SI unsigned long vaddvq_u64(uint64x2_t a) { return __N(ADDV, unsigned long, a, 0, 0, 0); }
__SI uint64x2_t vandq_u64(uint64x2_t a, uint64x2_t b) { return a & b; }
__SI uint64x2_t vorrq_u64(uint64x2_t a, uint64x2_t b) { return a | b; }
__SI uint64x2_t veorq_u64(uint64x2_t a, uint64x2_t b) { return a ^ b; }
__SI uint64x2_t vbicq_u64(uint64x2_t a, uint64x2_t b) { return __V(ANDNOT, b, a); }
__SI uint64x2_t vmvnq_u64(uint64x2_t a) { return ~a; }
#define vshlq_n_u64(a, n) ((uint64x2_t)(a) << (n))
#define vshrq_n_u64(a, n) ((uint64x2_t)(a) >> (n))
__SI uint64x2_t vshlq_u64(uint64x2_t a, int64x2_t b) { return __V(SHL, a, (uint64x2_t)b); }
__SI uint64x2_t vqaddq_u64(uint64x2_t a, uint64x2_t b) { return __V(ADDS, a, b); }
__SI uint64x2_t vqsubq_u64(uint64x2_t a, uint64x2_t b) { return __V(SUBS, a, b); }

__SI uint32x2_t vmovn_u64(uint64x2_t a) { return __N(XTN, uint32x2_t, a, 0, 0, 0); }
__SI uint32x2_t vqmovn_u64(uint64x2_t a) { return __N(QXTN, uint32x2_t, a, 0, 0, 0); }
__SI uint64x1_t vget_low_u64(uint64x2_t a) { uint64x1_t r; memcpy(&r, &a, 8); return r; }
__SI uint64x1_t vget_high_u64(uint64x2_t a) { uint64x1_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
__SI uint64x2_t vcombine_u64(uint64x1_t lo, uint64x1_t hi) { uint64x2_t r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }

/* float32x2_t */
__SI float32x2_t vld1_f32(const float *p) { float32x2_t r; memcpy(&r, p, 8); return r; }
__SI void vst1_f32(float *p, float32x2_t a) { memcpy(p, &a, 8); }
__SI float32x2_t vdup_n_f32(float x) { return __N(SPLAT, float32x2_t, x, 0, 0, 0); }
__SI float32x2_t vmov_n_f32(float x) { return vdup_n_f32(x); }
__SI float32x2_t vld1_dup_f32(const float *p) { return vdup_n_f32(*p); }
__SI float32x2_t vadd_f32(float32x2_t a, float32x2_t b) { return a + b; }
__SI float32x2_t vsub_f32(float32x2_t a, float32x2_t b) { return a - b; }
__SI float32x2_t vmul_f32(float32x2_t a, float32x2_t b) { return a * b; }
__SI uint32x2_t vceq_f32(float32x2_t a, float32x2_t b) { return (uint32x2_t)(a == b); }
__SI uint32x2_t vcgt_f32(float32x2_t a, float32x2_t b) { return (uint32x2_t)(a > b); }
__SI uint32x2_t vcge_f32(float32x2_t a, float32x2_t b) { return (uint32x2_t)(a >= b); }
__SI uint32x2_t vclt_f32(float32x2_t a, float32x2_t b) { return (uint32x2_t)(a < b); }
__SI uint32x2_t vcle_f32(float32x2_t a, float32x2_t b) { return (uint32x2_t)(a <= b); }
__SI float32x2_t vbsl_f32(uint32x2_t m, float32x2_t a, float32x2_t b) { return __N(BSL, float32x2_t, a, b, (float32x2_t)m, 0); }
__SI float32x2_t vzip1_f32(float32x2_t a, float32x2_t b) { return __V(UNPCKLO, a, b); }
__SI float32x2_t vzip2_f32(float32x2_t a, float32x2_t b) { return __V(UNPCKHI, a, b); }
__SI float32x2_t vuzp1_f32(float32x2_t a, float32x2_t b) { return __N(UZP1, float32x2_t, a, b, 0, 0); }
__SI float32x2_t vuzp2_f32(float32x2_t a, float32x2_t b) { return __N(UZP2, float32x2_t, a, b, 0, 0); }
__SI float32x2_t vtrn1_f32(float32x2_t a, float32x2_t b) { return __N(TRN1, float32x2_t, a, b, 0, 0); }
__SI float32x2_t vtrn2_f32(float32x2_t a, float32x2_t b) { return __N(TRN2, float32x2_t, a, b, 0, 0); }
#define vext_f32(a, b, n) __N(EXT, float32x2_t, (float32x2_t)(a), (float32x2_t)(b), 0, (n) * 4)
#define vget_lane_f32(a, n) (((float32x2_t)(a))[n])
#define vset_lane_f32(x, a, n) ({ float32x2_t __t = (a); __t[n] = (x); __t; })
#define vdup_lane_f32(a, n) __N(DUPL, float32x2_t, (float32x2_t)(a), 0, 0, n)
__SI float32x2_t vpadd_f32(float32x2_t a, float32x2_t b) { return __N(ADDP, float32x2_t, a, b, 0, 0); }
__SI float vaddv_f32(float32x2_t a) { return __N(ADDV, float, a, 0, 0, 0); }
__SI float32x2_t vdiv_f32(float32x2_t a, float32x2_t b) { return a / b; }
__SI float32x2_t vneg_f32(float32x2_t a) { return -a; }
__SI float32x2_t vabs_f32(float32x2_t a) { return __V(ABS, a, a); }
__SI float32x2_t vsqrt_f32(float32x2_t a) { return __V(SQRT, a, a); }
__SI float32x2_t vmax_f32(float32x2_t a, float32x2_t b) { return __V(MAX, a, b); }
__SI float32x2_t vmin_f32(float32x2_t a, float32x2_t b) { return __V(MIN, a, b); }
__SI float32x2_t vmul_n_f32(float32x2_t a, float x) { return a * x; }
__SI float32x2_t vmla_f32(float32x2_t a, float32x2_t b, float32x2_t c) { return a + b * c; }
__SI float32x2_t vfma_f32(float32x2_t a, float32x2_t b, float32x2_t c) { return __N(FMA, float32x2_t, b, c, a, 0); }
__SI float32x2_t vfms_f32(float32x2_t a, float32x2_t b, float32x2_t c) { return __N(FMS, float32x2_t, b, c, a, 0); }
__SI float32x2_t vfma_n_f32(float32x2_t a, float32x2_t b, float x) { return __N(FMA, float32x2_t, b, vdup_n_f32(x), a, 0); }
__SI float32x2_t vcvt_f32_s32(int32x2_t a) { return __N(CVTI2F, float32x2_t, a, 0, 0, 0); }
__SI float32x2_t vcvt_f32_u32(uint32x2_t a) { return __N(CVTI2F, float32x2_t, a, 0, 0, 0); }
__SI int32x2_t vcvt_s32_f32(float32x2_t a) { return __N(CVTF2I, int32x2_t, a, 0, 0, 0); }
__SI uint32x2_t vcvt_u32_f32(float32x2_t a) { return __N(CVTF2I, uint32x2_t, a, 0, 0, 1); }
__SI int32x2_t vcvtn_s32_f32(float32x2_t a) { return __N(CVTF2IR, int32x2_t, a, 0, 0, 0); }

/* float32x4_t */
__SI float32x4_t vld1q_f32(const float *p) { float32x4_t r; memcpy(&r, p, 16); return r; }
__SI void vst1q_f32(float *p, float32x4_t a) { memcpy(p, &a, 16); }
__SI float32x4_t vdupq_n_f32(float x) { return __N(SPLAT, float32x4_t, x, 0, 0, 0); }
__SI float32x4_t vmovq_n_f32(float x) { return vdupq_n_f32(x); }
__SI float32x4_t vld1q_dup_f32(const float *p) { return vdupq_n_f32(*p); }
__SI float32x4_t vaddq_f32(float32x4_t a, float32x4_t b) { return a + b; }
__SI float32x4_t vsubq_f32(float32x4_t a, float32x4_t b) { return a - b; }
__SI float32x4_t vmulq_f32(float32x4_t a, float32x4_t b) { return a * b; }
__SI uint32x4_t vceqq_f32(float32x4_t a, float32x4_t b) { return (uint32x4_t)(a == b); }
__SI uint32x4_t vcgtq_f32(float32x4_t a, float32x4_t b) { return (uint32x4_t)(a > b); }
__SI uint32x4_t vcgeq_f32(float32x4_t a, float32x4_t b) { return (uint32x4_t)(a >= b); }
__SI uint32x4_t vcltq_f32(float32x4_t a, float32x4_t b) { return (uint32x4_t)(a < b); }
__SI uint32x4_t vcleq_f32(float32x4_t a, float32x4_t b) { return (uint32x4_t)(a <= b); }
__SI float32x4_t vbslq_f32(uint32x4_t m, float32x4_t a, float32x4_t b) { return __N(BSL, float32x4_t, a, b, (float32x4_t)m, 0); }
__SI float32x4_t vzip1q_f32(float32x4_t a, float32x4_t b) { return __V(UNPCKLO, a, b); }
__SI float32x4_t vzip2q_f32(float32x4_t a, float32x4_t b) { return __V(UNPCKHI, a, b); }
__SI float32x4_t vuzp1q_f32(float32x4_t a, float32x4_t b) { return __N(UZP1, float32x4_t, a, b, 0, 0); }
__SI float32x4_t vuzp2q_f32(float32x4_t a, float32x4_t b) { return __N(UZP2, float32x4_t, a, b, 0, 0); }
__SI float32x4_t vtrn1q_f32(float32x4_t a, float32x4_t b) { return __N(TRN1, float32x4_t, a, b, 0, 0); }
__SI float32x4_t vtrn2q_f32(float32x4_t a, float32x4_t b) { return __N(TRN2, float32x4_t, a, b, 0, 0); }
#define vextq_f32(a, b, n) __N(EXT, float32x4_t, (float32x4_t)(a), (float32x4_t)(b), 0, (n) * 4)
#define vgetq_lane_f32(a, n) (((float32x4_t)(a))[n])
#define vsetq_lane_f32(x, a, n) ({ float32x4_t __t = (a); __t[n] = (x); __t; })
#define vdupq_laneq_f32(a, n) __N(DUPL, float32x4_t, (float32x4_t)(a), 0, 0, n)
__SI float32x4_t vpaddq_f32(float32x4_t a, float32x4_t b) { return __N(ADDP, float32x4_t, a, b, 0, 0); }
__SI float vaddvq_f32(float32x4_t a) { return __N(ADDV, float, a, 0, 0, 0); }
__SI float32x4_t vdivq_f32(float32x4_t a, float32x4_t b) { return a / b; }
__SI float32x4_t vnegq_f32(float32x4_t a) { return -a; }
__SI float32x4_t vabsq_f32(float32x4_t a) { return __V(ABS, a, a); }
__SI float32x4_t vsqrtq_f32(float32x4_t a) { return __V(SQRT, a, a); }
__SI float32x4_t vmaxq_f32(float32x4_t a, float32x4_t b) { return __V(MAX, a, b); }
__SI float32x4_t vminq_f32(float32x4_t a, float32x4_t b) { return __V(MIN, a, b); }
__SI float32x4_t vmulq_n_f32(float32x4_t a, float x) { return a * x; }
__SI float32x4_t vmlaq_f32(float32x4_t a, float32x4_t b, float32x4_t c) { return a + b * c; }
__SI float32x4_t vfmaq_f32(float32x4_t a, float32x4_t b, float32x4_t c) { return __N(FMA, float32x4_t, b, c, a, 0); }
__SI float32x4_t vfmsq_f32(float32x4_t a, float32x4_t b, float32x4_t c) { return __N(FMS, float32x4_t, b, c, a, 0); }
__SI float32x4_t vfmaq_n_f32(float32x4_t a, float32x4_t b, float x) { return __N(FMA, float32x4_t, b, vdupq_n_f32(x), a, 0); }
__SI float32x4_t vcvtq_f32_s32(int32x4_t a) { return __N(CVTI2F, float32x4_t, a, 0, 0, 0); }
__SI float32x4_t vcvtq_f32_u32(uint32x4_t a) { return __N(CVTI2F, float32x4_t, a, 0, 0, 0); }
__SI int32x4_t vcvtq_s32_f32(float32x4_t a) { return __N(CVTF2I, int32x4_t, a, 0, 0, 0); }
__SI uint32x4_t vcvtq_u32_f32(float32x4_t a) { return __N(CVTF2I, uint32x4_t, a, 0, 0, 1); }
__SI int32x4_t vcvtnq_s32_f32(float32x4_t a) { return __N(CVTF2IR, int32x4_t, a, 0, 0, 0); }

__SI float32x2_t vget_low_f32(float32x4_t a) { float32x2_t r; memcpy(&r, &a, 8); return r; }
__SI float32x2_t vget_high_f32(float32x4_t a) { float32x2_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
__SI float32x4_t vcombine_f32(float32x2_t lo, float32x2_t hi) { float32x4_t r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }

/* float64x1_t */
__SI float64x1_t vld1_f64(const double *p) { float64x1_t r; memcpy(&r, p, 8); return r; }
__SI void vst1_f64(double *p, float64x1_t a) { memcpy(p, &a, 8); }
__SI float64x1_t vdup_n_f64(double x) { return __N(SPLAT, float64x1_t, x, 0, 0, 0); }
__SI float64x1_t vmov_n_f64(double x) { return vdup_n_f64(x); }
__SI float64x1_t vld1_dup_f64(const double *p) { return vdup_n_f64(*p); }
__SI float64x1_t vadd_f64(float64x1_t a, float64x1_t b) { return a + b; }
__SI float64x1_t vsub_f64(float64x1_t a, float64x1_t b) { return a - b; }
__SI float64x1_t vmul_f64(float64x1_t a, float64x1_t b) { return a * b; }
__SI uint64x1_t vceq_f64(float64x1_t a, float64x1_t b) { return (uint64x1_t)(a == b); }
__SI uint64x1_t vcgt_f64(float64x1_t a, float64x1_t b) { return (uint64x1_t)(a > b); }
__SI uint64x1_t vcge_f64(float64x1_t a, float64x1_t b) { return (uint64x1_t)(a >= b); }
__SI uint64x1_t vclt_f64(float64x1_t a, float64x1_t b) { return (uint64x1_t)(a < b); }
__SI uint64x1_t vcle_f64(float64x1_t a, float64x1_t b) { return (uint64x1_t)(a <= b); }
__SI float64x1_t vbsl_f64(uint64x1_t m, float64x1_t a, float64x1_t b) { return __N(BSL, float64x1_t, a, b, (float64x1_t)m, 0); }
__SI float64x1_t vzip1_f64(float64x1_t a, float64x1_t b) { return __V(UNPCKLO, a, b); }
__SI float64x1_t vzip2_f64(float64x1_t a, float64x1_t b) { return __V(UNPCKHI, a, b); }
__SI float64x1_t vuzp1_f64(float64x1_t a, float64x1_t b) { return __N(UZP1, float64x1_t, a, b, 0, 0); }
__SI float64x1_t vuzp2_f64(float64x1_t a, float64x1_t b) { return __N(UZP2, float64x1_t, a, b, 0, 0); }
__SI float64x1_t vtrn1_f64(float64x1_t a, float64x1_t b) { return __N(TRN1, float64x1_t, a, b, 0, 0); }
__SI float64x1_t vtrn2_f64(float64x1_t a, float64x1_t b) { return __N(TRN2, float64x1_t, a, b, 0, 0); }
#define vext_f64(a, b, n) __N(EXT, float64x1_t, (float64x1_t)(a), (float64x1_t)(b), 0, (n) * 8)
#define vget_lane_f64(a, n) (((float64x1_t)(a))[n])
#define vset_lane_f64(x, a, n) ({ float64x1_t __t = (a); __t[n] = (x); __t; })
#define vdup_lane_f64(a, n) __N(DUPL, float64x1_t, (float64x1_t)(a), 0, 0, n)
__SI float64x1_t vpadd_f64(float64x1_t a, float64x1_t b) { return __N(ADDP, float64x1_t, a, b, 0, 0); }
__SI float64x1_t vdiv_f64(float64x1_t a, float64x1_t b) { return a / b; }
__SI float64x1_t vneg_f64(float64x1_t a) { return -a; }
__SI float64x1_t vabs_f64(float64x1_t a) { return __V(ABS, a, a); }
__SI float64x1_t vsqrt_f64(float64x1_t a) { return __V(SQRT, a, a); }
__SI float64x1_t vmax_f64(float64x1_t a, float64x1_t b) { return __V(MAX, a, b); }
__SI float64x1_t vmin_f64(float64x1_t a, float64x1_t b) { return __V(MIN, a, b); }
__SI float64x1_t vmul_n_f64(float64x1_t a, double x) { return a * x; }
__SI float64x1_t vmla_f64(float64x1_t a, float64x1_t b, float64x1_t c) { return a + b * c; }
__SI float64x1_t vfma_f64(float64x1_t a, float64x1_t b, float64x1_t c) { return __N(FMA, float64x1_t, b, c, a, 0); }
__SI float64x1_t vfms_f64(float64x1_t a, float64x1_t b, float64x1_t c) { return __N(FMS, float64x1_t, b, c, a, 0); }
__SI float64x1_t vfma_n_f64(float64x1_t a, float64x1_t b, double x) { return __N(FMA, float64x1_t, b, vdup_n_f64(x), a, 0); }
__SI float64x1_t vcvt_f64_s64(int64x1_t a) { return __N(CVTI2F, float64x1_t, a, 0, 0, 0); }
__SI float64x1_t vcvt_f64_u64(uint64x1_t a) { return __N(CVTI2F, float64x1_t, a, 0, 0, 0); }
__SI int64x1_t vcvt_s64_f64(float64x1_t a) { return __N(CVTF2I, int64x1_t, a, 0, 0, 0); }
__SI uint64x1_t vcvt_u64_f64(float64x1_t a) { return __N(CVTF2I, uint64x1_t, a, 0, 0, 1); }
__SI int64x1_t vcvtn_s64_f64(float64x1_t a) { return __N(CVTF2IR, int64x1_t, a, 0, 0, 0); }

/* float64x2_t */
__SI float64x2_t vld1q_f64(const double *p) { float64x2_t r; memcpy(&r, p, 16); return r; }
__SI void vst1q_f64(double *p, float64x2_t a) { memcpy(p, &a, 16); }
__SI float64x2_t vdupq_n_f64(double x) { return __N(SPLAT, float64x2_t, x, 0, 0, 0); }
__SI float64x2_t vmovq_n_f64(double x) { return vdupq_n_f64(x); }
__SI float64x2_t vld1q_dup_f64(const double *p) { return vdupq_n_f64(*p); }
__SI float64x2_t vaddq_f64(float64x2_t a, float64x2_t b) { return a + b; }
__SI float64x2_t vsubq_f64(float64x2_t a, float64x2_t b) { return a - b; }
__SI float64x2_t vmulq_f64(float64x2_t a, float64x2_t b) { return a * b; }
__SI uint64x2_t vceqq_f64(float64x2_t a, float64x2_t b) { return (uint64x2_t)(a == b); }
__SI uint64x2_t vcgtq_f64(float64x2_t a, float64x2_t b) { return (uint64x2_t)(a > b); }
__SI uint64x2_t vcgeq_f64(float64x2_t a, float64x2_t b) { return (uint64x2_t)(a >= b); }
__SI uint64x2_t vcltq_f64(float64x2_t a, float64x2_t b) { return (uint64x2_t)(a < b); }
__SI uint64x2_t vcleq_f64(float64x2_t a, float64x2_t b) { return (uint64x2_t)(a <= b); }
__SI float64x2_t vbslq_f64(uint64x2_t m, float64x2_t a, float64x2_t b) { return __N(BSL, float64x2_t, a, b, (float64x2_t)m, 0); }
__SI float64x2_t vzip1q_f64(float64x2_t a, float64x2_t b) { return __V(UNPCKLO, a, b); }
__SI float64x2_t vzip2q_f64(float64x2_t a, float64x2_t b) { return __V(UNPCKHI, a, b); }
__SI float64x2_t vuzp1q_f64(float64x2_t a, float64x2_t b) { return __N(UZP1, float64x2_t, a, b, 0, 0); }
__SI float64x2_t vuzp2q_f64(float64x2_t a, float64x2_t b) { return __N(UZP2, float64x2_t, a, b, 0, 0); }
__SI float64x2_t vtrn1q_f64(float64x2_t a, float64x2_t b) { return __N(TRN1, float64x2_t, a, b, 0, 0); }
__SI float64x2_t vtrn2q_f64(float64x2_t a, float64x2_t b) { return __N(TRN2, float64x2_t, a, b, 0, 0); }
#define vextq_f64(a, b, n) __N(EXT, float64x2_t, (float64x2_t)(a), (float64x2_t)(b), 0, (n) * 8)
#define vgetq_lane_f64(a, n) (((float64x2_t)(a))[n])
#define vsetq_lane_f64(x, a, n) ({ float64x2_t __t = (a); __t[n] = (x); __t; })
#define vdupq_laneq_f64(a, n) __N(DUPL, float64x2_t, (float64x2_t)(a), 0, 0, n)
__SI float64x2_t vpaddq_f64(float64x2_t a, float64x2_t b) { return __N(ADDP, float64x2_t, a, b, 0, 0); }
__SI double vaddvq_f64(float64x2_t a) { return __N(ADDV, double, a, 0, 0, 0); }
__SI float64x2_t vdivq_f64(float64x2_t a, float64x2_t b) { return a / b; }
__SI float64x2_t vnegq_f64(float64x2_t a) { return -a; }
__SI float64x2_t vabsq_f64(float64x2_t a) { return __V(ABS, a, a); }
__SI float64x2_t vsqrtq_f64(float64x2_t a) { return __V(SQRT, a, a); }
__SI float64x2_t vmaxq_f64(float64x2_t a, float64x2_t b) { return __V(MAX, a, b); }
__SI float64x2_t vminq_f64(float64x2_t a, float64x2_t b) { return __V(MIN, a, b); }
__SI float64x2_t vmulq_n_f64(float64x2_t a, double x) { return a * x; }
__SI float64x2_t vmlaq_f64(float64x2_t a, float64x2_t b, float64x2_t c) { return a + b * c; }
__SI float64x2_t vfmaq_f64(float64x2_t a, float64x2_t b, float64x2_t c) { return __N(FMA, float64x2_t, b, c, a, 0); }
__SI float64x2_t vfmsq_f64(float64x2_t a, float64x2_t b, float64x2_t c) { return __N(FMS, float64x2_t, b, c, a, 0); }
__SI float64x2_t vfmaq_n_f64(float64x2_t a, float64x2_t b, double x) { return __N(FMA, float64x2_t, b, vdupq_n_f64(x), a, 0); }
__SI float64x2_t vcvtq_f64_s64(int64x2_t a) { return __N(CVTI2F, float64x2_t, a, 0, 0, 0); }
__SI float64x2_t vcvtq_f64_u64(uint64x2_t a) { return __N(CVTI2F, float64x2_t, a, 0, 0, 0); }
__SI int64x2_t vcvtq_s64_f64(float64x2_t a) { return __N(CVTF2I, int64x2_t, a, 0, 0, 0); }
__SI uint64x2_t vcvtq_u64_f64(float64x2_t a) { return __N(CVTF2I, uint64x2_t, a, 0, 0, 1); }
__SI int64x2_t vcvtnq_s64_f64(float64x2_t a) { return __N(CVTF2IR, int64x2_t, a, 0, 0, 0); }

__SI float64x1_t vget_low_f64(float64x2_t a) { float64x1_t r; memcpy(&r, &a, 8); return r; }
__SI float64x1_t vget_high_f64(float64x2_t a) { float64x1_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
__SI float64x2_t vcombine_f64(float64x1_t lo, float64x1_t hi) { float64x2_t r; memcpy(&r, &lo, 8); memcpy((char *)&r + 8, &hi, 8); return r; }

/* tables, half precision, reinterpretation */
__SI uint8x16_t vqtbl1q_u8(uint8x16_t t, uint8x16_t i) { return __N(TBL, uint8x16_t, t, i, 0, 0); }
__SI uint8x8_t vqtbl1_u8(uint8x16_t t, uint8x8_t i) { return __N(TBL, uint8x8_t, t, i, 0, 0); }
__SI int8x16_t vqtbl1q_s8(int8x16_t t, uint8x16_t i) { return __N(TBL, int8x16_t, t, i, 0, 0); }
__SI int8x8_t vqtbl1_s8(int8x16_t t, uint8x8_t i) { return __N(TBL, int8x8_t, t, i, 0, 0); }
__SI float32x4_t vcvt_f32_f16(float16x4_t a) { return __N(FCVTL, float32x4_t, a, 0, 0, 0); }
__SI float32x4_t vcvt_high_f32_f16(float16x8_t a) { return __N(FCVTL2, float32x4_t, a, 0, 0, 0); }
__SI float16x4_t vcvt_f16_f32(float32x4_t a) { return __N(FCVTN, float16x4_t, a, 0, 0, 0); }
__SI float16x4_t vld1_f16(const void *p) { float16x4_t r; memcpy(&r, p, 8); return r; }
__SI float16x8_t vld1q_f16(const void *p) { float16x8_t r; memcpy(&r, p, 16); return r; }
__SI void vst1_f16(void *p, float16x4_t a) { memcpy(p, &a, 8); }
__SI float16x4_t vget_low_f16(float16x8_t a) { float16x4_t r; memcpy(&r, &a, 8); return r; }
__SI float16x4_t vget_high_f16(float16x8_t a) { float16x4_t r; memcpy(&r, (char *)&a + 8, 8); return r; }
#define vreinterpret_s8_u8(x) ((int8x8_t)(x))
#define vreinterpret_s8_s16(x) ((int8x8_t)(x))
#define vreinterpret_s8_u16(x) ((int8x8_t)(x))
#define vreinterpret_s8_s32(x) ((int8x8_t)(x))
#define vreinterpret_s8_u32(x) ((int8x8_t)(x))
#define vreinterpret_s8_s64(x) ((int8x8_t)(x))
#define vreinterpret_s8_u64(x) ((int8x8_t)(x))
#define vreinterpret_s8_f32(x) ((int8x8_t)(x))
#define vreinterpret_s8_f64(x) ((int8x8_t)(x))
#define vreinterpret_s8_f16(x) ((int8x8_t)(x))
#define vreinterpret_u8_s8(x) ((uint8x8_t)(x))
#define vreinterpret_u8_s16(x) ((uint8x8_t)(x))
#define vreinterpret_u8_u16(x) ((uint8x8_t)(x))
#define vreinterpret_u8_s32(x) ((uint8x8_t)(x))
#define vreinterpret_u8_u32(x) ((uint8x8_t)(x))
#define vreinterpret_u8_s64(x) ((uint8x8_t)(x))
#define vreinterpret_u8_u64(x) ((uint8x8_t)(x))
#define vreinterpret_u8_f32(x) ((uint8x8_t)(x))
#define vreinterpret_u8_f64(x) ((uint8x8_t)(x))
#define vreinterpret_u8_f16(x) ((uint8x8_t)(x))
#define vreinterpret_s16_s8(x) ((int16x4_t)(x))
#define vreinterpret_s16_u8(x) ((int16x4_t)(x))
#define vreinterpret_s16_u16(x) ((int16x4_t)(x))
#define vreinterpret_s16_s32(x) ((int16x4_t)(x))
#define vreinterpret_s16_u32(x) ((int16x4_t)(x))
#define vreinterpret_s16_s64(x) ((int16x4_t)(x))
#define vreinterpret_s16_u64(x) ((int16x4_t)(x))
#define vreinterpret_s16_f32(x) ((int16x4_t)(x))
#define vreinterpret_s16_f64(x) ((int16x4_t)(x))
#define vreinterpret_s16_f16(x) ((int16x4_t)(x))
#define vreinterpret_u16_s8(x) ((uint16x4_t)(x))
#define vreinterpret_u16_u8(x) ((uint16x4_t)(x))
#define vreinterpret_u16_s16(x) ((uint16x4_t)(x))
#define vreinterpret_u16_s32(x) ((uint16x4_t)(x))
#define vreinterpret_u16_u32(x) ((uint16x4_t)(x))
#define vreinterpret_u16_s64(x) ((uint16x4_t)(x))
#define vreinterpret_u16_u64(x) ((uint16x4_t)(x))
#define vreinterpret_u16_f32(x) ((uint16x4_t)(x))
#define vreinterpret_u16_f64(x) ((uint16x4_t)(x))
#define vreinterpret_u16_f16(x) ((uint16x4_t)(x))
#define vreinterpret_s32_s8(x) ((int32x2_t)(x))
#define vreinterpret_s32_u8(x) ((int32x2_t)(x))
#define vreinterpret_s32_s16(x) ((int32x2_t)(x))
#define vreinterpret_s32_u16(x) ((int32x2_t)(x))
#define vreinterpret_s32_u32(x) ((int32x2_t)(x))
#define vreinterpret_s32_s64(x) ((int32x2_t)(x))
#define vreinterpret_s32_u64(x) ((int32x2_t)(x))
#define vreinterpret_s32_f32(x) ((int32x2_t)(x))
#define vreinterpret_s32_f64(x) ((int32x2_t)(x))
#define vreinterpret_s32_f16(x) ((int32x2_t)(x))
#define vreinterpret_u32_s8(x) ((uint32x2_t)(x))
#define vreinterpret_u32_u8(x) ((uint32x2_t)(x))
#define vreinterpret_u32_s16(x) ((uint32x2_t)(x))
#define vreinterpret_u32_u16(x) ((uint32x2_t)(x))
#define vreinterpret_u32_s32(x) ((uint32x2_t)(x))
#define vreinterpret_u32_s64(x) ((uint32x2_t)(x))
#define vreinterpret_u32_u64(x) ((uint32x2_t)(x))
#define vreinterpret_u32_f32(x) ((uint32x2_t)(x))
#define vreinterpret_u32_f64(x) ((uint32x2_t)(x))
#define vreinterpret_u32_f16(x) ((uint32x2_t)(x))
#define vreinterpret_s64_s8(x) ((int64x1_t)(x))
#define vreinterpret_s64_u8(x) ((int64x1_t)(x))
#define vreinterpret_s64_s16(x) ((int64x1_t)(x))
#define vreinterpret_s64_u16(x) ((int64x1_t)(x))
#define vreinterpret_s64_s32(x) ((int64x1_t)(x))
#define vreinterpret_s64_u32(x) ((int64x1_t)(x))
#define vreinterpret_s64_u64(x) ((int64x1_t)(x))
#define vreinterpret_s64_f32(x) ((int64x1_t)(x))
#define vreinterpret_s64_f64(x) ((int64x1_t)(x))
#define vreinterpret_s64_f16(x) ((int64x1_t)(x))
#define vreinterpret_u64_s8(x) ((uint64x1_t)(x))
#define vreinterpret_u64_u8(x) ((uint64x1_t)(x))
#define vreinterpret_u64_s16(x) ((uint64x1_t)(x))
#define vreinterpret_u64_u16(x) ((uint64x1_t)(x))
#define vreinterpret_u64_s32(x) ((uint64x1_t)(x))
#define vreinterpret_u64_u32(x) ((uint64x1_t)(x))
#define vreinterpret_u64_s64(x) ((uint64x1_t)(x))
#define vreinterpret_u64_f32(x) ((uint64x1_t)(x))
#define vreinterpret_u64_f64(x) ((uint64x1_t)(x))
#define vreinterpret_u64_f16(x) ((uint64x1_t)(x))
#define vreinterpret_f32_s8(x) ((float32x2_t)(x))
#define vreinterpret_f32_u8(x) ((float32x2_t)(x))
#define vreinterpret_f32_s16(x) ((float32x2_t)(x))
#define vreinterpret_f32_u16(x) ((float32x2_t)(x))
#define vreinterpret_f32_s32(x) ((float32x2_t)(x))
#define vreinterpret_f32_u32(x) ((float32x2_t)(x))
#define vreinterpret_f32_s64(x) ((float32x2_t)(x))
#define vreinterpret_f32_u64(x) ((float32x2_t)(x))
#define vreinterpret_f32_f64(x) ((float32x2_t)(x))
#define vreinterpret_f32_f16(x) ((float32x2_t)(x))
#define vreinterpret_f64_s8(x) ((float64x1_t)(x))
#define vreinterpret_f64_u8(x) ((float64x1_t)(x))
#define vreinterpret_f64_s16(x) ((float64x1_t)(x))
#define vreinterpret_f64_u16(x) ((float64x1_t)(x))
#define vreinterpret_f64_s32(x) ((float64x1_t)(x))
#define vreinterpret_f64_u32(x) ((float64x1_t)(x))
#define vreinterpret_f64_s64(x) ((float64x1_t)(x))
#define vreinterpret_f64_u64(x) ((float64x1_t)(x))
#define vreinterpret_f64_f32(x) ((float64x1_t)(x))
#define vreinterpret_f64_f16(x) ((float64x1_t)(x))
#define vreinterpret_f16_s8(x) ((float16x4_t)(x))
#define vreinterpret_f16_u8(x) ((float16x4_t)(x))
#define vreinterpret_f16_s16(x) ((float16x4_t)(x))
#define vreinterpret_f16_u16(x) ((float16x4_t)(x))
#define vreinterpret_f16_s32(x) ((float16x4_t)(x))
#define vreinterpret_f16_u32(x) ((float16x4_t)(x))
#define vreinterpret_f16_s64(x) ((float16x4_t)(x))
#define vreinterpret_f16_u64(x) ((float16x4_t)(x))
#define vreinterpret_f16_f32(x) ((float16x4_t)(x))
#define vreinterpret_f16_f64(x) ((float16x4_t)(x))
#define vreinterpretq_s8_u8(x) ((int8x16_t)(x))
#define vreinterpretq_s8_s16(x) ((int8x16_t)(x))
#define vreinterpretq_s8_u16(x) ((int8x16_t)(x))
#define vreinterpretq_s8_s32(x) ((int8x16_t)(x))
#define vreinterpretq_s8_u32(x) ((int8x16_t)(x))
#define vreinterpretq_s8_s64(x) ((int8x16_t)(x))
#define vreinterpretq_s8_u64(x) ((int8x16_t)(x))
#define vreinterpretq_s8_f32(x) ((int8x16_t)(x))
#define vreinterpretq_s8_f64(x) ((int8x16_t)(x))
#define vreinterpretq_s8_f16(x) ((int8x16_t)(x))
#define vreinterpretq_u8_s8(x) ((uint8x16_t)(x))
#define vreinterpretq_u8_s16(x) ((uint8x16_t)(x))
#define vreinterpretq_u8_u16(x) ((uint8x16_t)(x))
#define vreinterpretq_u8_s32(x) ((uint8x16_t)(x))
#define vreinterpretq_u8_u32(x) ((uint8x16_t)(x))
#define vreinterpretq_u8_s64(x) ((uint8x16_t)(x))
#define vreinterpretq_u8_u64(x) ((uint8x16_t)(x))
#define vreinterpretq_u8_f32(x) ((uint8x16_t)(x))
#define vreinterpretq_u8_f64(x) ((uint8x16_t)(x))
#define vreinterpretq_u8_f16(x) ((uint8x16_t)(x))
#define vreinterpretq_s16_s8(x) ((int16x8_t)(x))
#define vreinterpretq_s16_u8(x) ((int16x8_t)(x))
#define vreinterpretq_s16_u16(x) ((int16x8_t)(x))
#define vreinterpretq_s16_s32(x) ((int16x8_t)(x))
#define vreinterpretq_s16_u32(x) ((int16x8_t)(x))
#define vreinterpretq_s16_s64(x) ((int16x8_t)(x))
#define vreinterpretq_s16_u64(x) ((int16x8_t)(x))
#define vreinterpretq_s16_f32(x) ((int16x8_t)(x))
#define vreinterpretq_s16_f64(x) ((int16x8_t)(x))
#define vreinterpretq_s16_f16(x) ((int16x8_t)(x))
#define vreinterpretq_u16_s8(x) ((uint16x8_t)(x))
#define vreinterpretq_u16_u8(x) ((uint16x8_t)(x))
#define vreinterpretq_u16_s16(x) ((uint16x8_t)(x))
#define vreinterpretq_u16_s32(x) ((uint16x8_t)(x))
#define vreinterpretq_u16_u32(x) ((uint16x8_t)(x))
#define vreinterpretq_u16_s64(x) ((uint16x8_t)(x))
#define vreinterpretq_u16_u64(x) ((uint16x8_t)(x))
#define vreinterpretq_u16_f32(x) ((uint16x8_t)(x))
#define vreinterpretq_u16_f64(x) ((uint16x8_t)(x))
#define vreinterpretq_u16_f16(x) ((uint16x8_t)(x))
#define vreinterpretq_s32_s8(x) ((int32x4_t)(x))
#define vreinterpretq_s32_u8(x) ((int32x4_t)(x))
#define vreinterpretq_s32_s16(x) ((int32x4_t)(x))
#define vreinterpretq_s32_u16(x) ((int32x4_t)(x))
#define vreinterpretq_s32_u32(x) ((int32x4_t)(x))
#define vreinterpretq_s32_s64(x) ((int32x4_t)(x))
#define vreinterpretq_s32_u64(x) ((int32x4_t)(x))
#define vreinterpretq_s32_f32(x) ((int32x4_t)(x))
#define vreinterpretq_s32_f64(x) ((int32x4_t)(x))
#define vreinterpretq_s32_f16(x) ((int32x4_t)(x))
#define vreinterpretq_u32_s8(x) ((uint32x4_t)(x))
#define vreinterpretq_u32_u8(x) ((uint32x4_t)(x))
#define vreinterpretq_u32_s16(x) ((uint32x4_t)(x))
#define vreinterpretq_u32_u16(x) ((uint32x4_t)(x))
#define vreinterpretq_u32_s32(x) ((uint32x4_t)(x))
#define vreinterpretq_u32_s64(x) ((uint32x4_t)(x))
#define vreinterpretq_u32_u64(x) ((uint32x4_t)(x))
#define vreinterpretq_u32_f32(x) ((uint32x4_t)(x))
#define vreinterpretq_u32_f64(x) ((uint32x4_t)(x))
#define vreinterpretq_u32_f16(x) ((uint32x4_t)(x))
#define vreinterpretq_s64_s8(x) ((int64x2_t)(x))
#define vreinterpretq_s64_u8(x) ((int64x2_t)(x))
#define vreinterpretq_s64_s16(x) ((int64x2_t)(x))
#define vreinterpretq_s64_u16(x) ((int64x2_t)(x))
#define vreinterpretq_s64_s32(x) ((int64x2_t)(x))
#define vreinterpretq_s64_u32(x) ((int64x2_t)(x))
#define vreinterpretq_s64_u64(x) ((int64x2_t)(x))
#define vreinterpretq_s64_f32(x) ((int64x2_t)(x))
#define vreinterpretq_s64_f64(x) ((int64x2_t)(x))
#define vreinterpretq_s64_f16(x) ((int64x2_t)(x))
#define vreinterpretq_u64_s8(x) ((uint64x2_t)(x))
#define vreinterpretq_u64_u8(x) ((uint64x2_t)(x))
#define vreinterpretq_u64_s16(x) ((uint64x2_t)(x))
#define vreinterpretq_u64_u16(x) ((uint64x2_t)(x))
#define vreinterpretq_u64_s32(x) ((uint64x2_t)(x))
#define vreinterpretq_u64_u32(x) ((uint64x2_t)(x))
#define vreinterpretq_u64_s64(x) ((uint64x2_t)(x))
#define vreinterpretq_u64_f32(x) ((uint64x2_t)(x))
#define vreinterpretq_u64_f64(x) ((uint64x2_t)(x))
#define vreinterpretq_u64_f16(x) ((uint64x2_t)(x))
#define vreinterpretq_f32_s8(x) ((float32x4_t)(x))
#define vreinterpretq_f32_u8(x) ((float32x4_t)(x))
#define vreinterpretq_f32_s16(x) ((float32x4_t)(x))
#define vreinterpretq_f32_u16(x) ((float32x4_t)(x))
#define vreinterpretq_f32_s32(x) ((float32x4_t)(x))
#define vreinterpretq_f32_u32(x) ((float32x4_t)(x))
#define vreinterpretq_f32_s64(x) ((float32x4_t)(x))
#define vreinterpretq_f32_u64(x) ((float32x4_t)(x))
#define vreinterpretq_f32_f64(x) ((float32x4_t)(x))
#define vreinterpretq_f32_f16(x) ((float32x4_t)(x))
#define vreinterpretq_f64_s8(x) ((float64x2_t)(x))
#define vreinterpretq_f64_u8(x) ((float64x2_t)(x))
#define vreinterpretq_f64_s16(x) ((float64x2_t)(x))
#define vreinterpretq_f64_u16(x) ((float64x2_t)(x))
#define vreinterpretq_f64_s32(x) ((float64x2_t)(x))
#define vreinterpretq_f64_u32(x) ((float64x2_t)(x))
#define vreinterpretq_f64_s64(x) ((float64x2_t)(x))
#define vreinterpretq_f64_u64(x) ((float64x2_t)(x))
#define vreinterpretq_f64_f32(x) ((float64x2_t)(x))
#define vreinterpretq_f64_f16(x) ((float64x2_t)(x))
#define vreinterpretq_f16_s8(x) ((float16x8_t)(x))
#define vreinterpretq_f16_u8(x) ((float16x8_t)(x))
#define vreinterpretq_f16_s16(x) ((float16x8_t)(x))
#define vreinterpretq_f16_u16(x) ((float16x8_t)(x))
#define vreinterpretq_f16_s32(x) ((float16x8_t)(x))
#define vreinterpretq_f16_u32(x) ((float16x8_t)(x))
#define vreinterpretq_f16_s64(x) ((float16x8_t)(x))
#define vreinterpretq_f16_u64(x) ((float16x8_t)(x))
#define vreinterpretq_f16_f32(x) ((float16x8_t)(x))
#define vreinterpretq_f16_f64(x) ((float16x8_t)(x))

#ifdef __ARM_FEATURE_DOTPROD
/* the dot product (ARMv8.2): each 32-bit lane += the sum of 4 byte products */
__SI int32x4_t vdotq_s32(int32x4_t acc, int8x16_t a, int8x16_t b) { return __N(DOT, int32x4_t, a, b, acc, 0); }
__SI uint32x4_t vdotq_u32(uint32x4_t acc, uint8x16_t a, uint8x16_t b) { return __N(DOT, uint32x4_t, a, b, acc, 0); }
__SI int32x2_t vdot_s32(int32x2_t acc, int8x8_t a, int8x8_t b) { return __N(DOT, int32x2_t, a, b, acc, 0); }
__SI uint32x2_t vdot_u32(uint32x2_t acc, uint8x8_t a, uint8x8_t b) { return __N(DOT, uint32x2_t, a, b, acc, 0); }
#define vdotq_laneq_s32(acc, a, b, n) __N(DOTL, int32x4_t, (int8x16_t)(a), (int8x16_t)(b), (int32x4_t)(acc), n)
#define vdotq_laneq_u32(acc, a, b, n) __N(DOTL, uint32x4_t, (uint8x16_t)(a), (uint8x16_t)(b), (uint32x4_t)(acc), n)
#define vdotq_lane_s32(acc, a, b, n) __N(DOTL, int32x4_t, (int8x16_t)(a), (int8x8_t)(b), (int32x4_t)(acc), n)
#endif
#endif
