#!/usr/bin/env python3
# Copyright (C) 2026 Olivier Moulin
# Part of SIEOS, released under the GNU General Public License version 3
# (GPL-3.0); see the LICENSE file.
"""mkksyms.py NM-OUTPUT OUT.S - the kernel's exported symbol table (every global
symbol of the kernel, from nm of the first link), sorted by name, for the driver
loader (kernel/modload.c).  An empty table without NM-OUTPUT ("-")."""
import sys
syms = {}
if sys.argv[1] != '-':
    for line in open(sys.argv[1]):
        p = line.split()
        if len(p) == 3 and p[1] in 'TDBRVW' and not p[2].startswith(('ksyms_', '_kernel_')):
            syms[p[2]] = int(p[0], 16)
names = sorted(syms)
out = ['/* generated by tools/mkksyms.py: the kernel symbols drivers link against */',
       '    .section .ksyms, "a"', '    .balign 8',
       '    .global ksyms_count, ksyms_table, ksyms_names',
       f'ksyms_count: .quad {len(names)}', 'ksyms_table:']
off = 0
for n in names:
    out.append(f'    .quad 0x{syms[n]:x}, {off}')
    off += len(n) + 1
out.append('ksyms_names:')
for n in names:
    out.append(f'    .asciz "{n}"')
out.append('    .byte 0')
open(sys.argv[2], 'w').write('\n'.join(out) + '\n')
