#!/usr/bin/env python3
# Copyright (C) 2026 Olivier Moulin
# Part of SIEOS, released under the GNU General Public License version 3
# (GPL-3.0); see the LICENSE file.
"""Convert a PSF1/PSF2 console font (8 pixels wide) into a C array indexed by
code point 0..255 (Latin-1), using the font's Unicode table when present."""
import gzip, struct, sys

def load(path):
    data = gzip.open(path).read() if path.endswith('.gz') else open(path, 'rb').read()
    if data[:2] == b'\x36\x04':                       # PSF1
        mode, h = data[2], data[3]
        n = 512 if mode & 1 else 256
        glyphs = [data[4 + i*h: 4 + (i+1)*h] for i in range(n)]
        table = {}
        if mode & 2:
            p = 4 + n*h
            for i in range(n):
                while True:
                    (u,) = struct.unpack_from('<H', data, p); p += 2
                    if u == 0xFFFF: break
                    if u != 0xFFFE: table.setdefault(u, i)
        return 8, h, glyphs, table
    magic, ver, hdr, flags, n, cb, h, w = struct.unpack_from('<8I', data)
    assert magic == 0x864ab572 and w == 8
    glyphs = [data[hdr + i*cb: hdr + (i+1)*cb] for i in range(n)]
    table = {}
    if flags & 1:
        p = hdr + n*cb
        for i in range(n):
            while data[p] != 0xFF:
                if data[p] == 0xFE: p += 1; continue
                b = data[p]; ln = 1 if b < 0x80 else 2 if b < 0xE0 else 3 if b < 0xF0 else 4
                table.setdefault(ord(data[p:p+ln].decode('utf-8')), i); p += ln
            p += 1
    return w, h, glyphs, table

w, h, glyphs, table = load(sys.argv[1])
assert h == 16, h
out = ['/* Generated by tools/psf2c.py from %s - do not edit. */' % sys.argv[1].split('/')[-1],
       '#include <stdint.h>', '', 'const uint8_t font8x16[256][16] = {']
for cp in range(256):
    idx = table.get(cp, cp if not table else table.get(0xFFFD, table.get(ord('?'), 0)))
    if cp < 32 or 127 <= cp < 160:
        g = bytes(16)
    else:
        g = glyphs[idx]
    out.append('    { %s },' % ', '.join('0x%02x' % b for b in g))
out.append('};')
print('\n'.join(out))
