/* SIEOS: Solaris open flags and fcntl commands (from the ABI headers). */
@DEFINES fcntl.h:O_(CREAT|EXCL|NOCTTY|TRUNC|APPEND|NONBLOCK|NDELAY|DSYNC|SYNC|RSYNC|DIRECTORY|NOFOLLOW|CLOEXEC|LARGEFILE|XATTR|NOLINKS)@
#define O_PATH     0x00200000
#define O_TMPFILE  0x10000000

@DEFINES fcntl.h:F_(DUPFD|GETFD|SETFD|GETFL|SETFL|GETLK|SETLK|SETLKW|GETOWN|SETOWN)@
#define F_SETOWN_EX 0x7ff0
#define F_GETOWN_EX 0x7ff1
