/* SIEOS: Solaris socket types and options (from the ABI headers). */
@DEFINES socket.h:SOCK_(STREAM|DGRAM|RAW|RDM|SEQPACKET|CLOEXEC|NONBLOCK|NDELAY)@
@DEFINES socket.h:SOL_SOCKET@
@DEFINES socket.h:SO_(DEBUG|ACCEPTCONN|REUSEADDR|KEEPALIVE|DONTROUTE|BROADCAST|USELOOPBACK|LINGER|OOBINLINE|SNDBUF|RCVBUF|SNDLOWAT|RCVLOWAT|SNDTIMEO|RCVTIMEO|ERROR|TYPE)@
#define SO_TIMESTAMP 0x1013
#define SO_TIMESTAMPNS 0x1014
#define SO_TIMESTAMPING 0x1015
#define SO_PROTOCOL 0x1016
#define SO_DOMAIN   0x100c
#define SO_PEERCRED 0x1017
#define SO_PASSCRED 0x1018
#define SO_REUSEPORT 0x100e
#define SO_PRIORITY 0x100f
#define SO_SNDBUFFORCE 0x101a
#define SO_RCVBUFFORCE 0x101b
